// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_rules.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAIRules = `-- name: CreateAIRules :one
INSERT INTO ai_rules (id, business_id, assistant_name, personality, tone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, business_id, assistant_name, avatar_url, avatar_model_path, personality, tone, language, behavioral_rules, tool_instructions, idle_timeout_seconds, voice_preset, voice_gender
`

type CreateAIRulesParams struct {
	ID            string `json:"id"`
	BusinessID    string `json:"business_id"`
	AssistantName string `json:"assistant_name"`
	Personality   string `json:"personality"`
	Tone          string `json:"tone"`
}

func (q *Queries) CreateAIRules(ctx context.Context, arg CreateAIRulesParams) (AiRule, error) {
	row := q.db.QueryRow(ctx, createAIRules,
		arg.ID,
		arg.BusinessID,
		arg.AssistantName,
		arg.Personality,
		arg.Tone,
	)
	var i AiRule
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.AssistantName,
		&i.AvatarUrl,
		&i.AvatarModelPath,
		&i.Personality,
		&i.Tone,
		&i.Language,
		&i.BehavioralRules,
		&i.ToolInstructions,
		&i.IdleTimeoutSeconds,
		&i.VoicePreset,
		&i.VoiceGender,
	)
	return i, err
}

const getAIRules = `-- name: GetAIRules :one
SELECT id, business_id, assistant_name, avatar_url, avatar_model_path, personality, tone, language, behavioral_rules, tool_instructions, idle_timeout_seconds, voice_preset, voice_gender FROM ai_rules WHERE business_id = $1
`

func (q *Queries) GetAIRules(ctx context.Context, businessID string) (AiRule, error) {
	row := q.db.QueryRow(ctx, getAIRules, businessID)
	var i AiRule
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.AssistantName,
		&i.AvatarUrl,
		&i.AvatarModelPath,
		&i.Personality,
		&i.Tone,
		&i.Language,
		&i.BehavioralRules,
		&i.ToolInstructions,
		&i.IdleTimeoutSeconds,
		&i.VoicePreset,
		&i.VoiceGender,
	)
	return i, err
}

const setAIRulesAvatarURL = `-- name: SetAIRulesAvatarURL :one
UPDATE ai_rules SET avatar_url = $2 WHERE business_id = $1
RETURNING id, business_id, assistant_name, avatar_url, avatar_model_path, personality, tone, language, behavioral_rules, tool_instructions, idle_timeout_seconds, voice_preset, voice_gender
`

type SetAIRulesAvatarURLParams struct {
	BusinessID string `json:"business_id"`
	AvatarUrl  string `json:"avatar_url"`
}

func (q *Queries) SetAIRulesAvatarURL(ctx context.Context, arg SetAIRulesAvatarURLParams) (AiRule, error) {
	row := q.db.QueryRow(ctx, setAIRulesAvatarURL, arg.BusinessID, arg.AvatarUrl)
	var i AiRule
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.AssistantName,
		&i.AvatarUrl,
		&i.AvatarModelPath,
		&i.Personality,
		&i.Tone,
		&i.Language,
		&i.BehavioralRules,
		&i.ToolInstructions,
		&i.IdleTimeoutSeconds,
		&i.VoicePreset,
		&i.VoiceGender,
	)
	return i, err
}

const updateAIRules = `-- name: UpdateAIRules :one
UPDATE ai_rules SET
  assistant_name = COALESCE($1, assistant_name),
  avatar_model_path = COALESCE($2, avatar_model_path),
  personality = COALESCE($3, personality),
  tone = COALESCE($4, tone),
  language = COALESCE($5, language),
  behavioral_rules = COALESCE($6, behavioral_rules),
  tool_instructions = COALESCE($7, tool_instructions),
  idle_timeout_seconds = COALESCE($8, idle_timeout_seconds),
  voice_preset = COALESCE($9, voice_preset),
  voice_gender = COALESCE($10, voice_gender)
WHERE business_id = $11
RETURNING id, business_id, assistant_name, avatar_url, avatar_model_path, personality, tone, language, behavioral_rules, tool_instructions, idle_timeout_seconds, voice_preset, voice_gender
`

type UpdateAIRulesParams struct {
	AssistantName      pgtype.Text `json:"assistant_name"`
	AvatarModelPath    pgtype.Text `json:"avatar_model_path"`
	Personality        pgtype.Text `json:"personality"`
	Tone               pgtype.Text `json:"tone"`
	Language           pgtype.Text `json:"language"`
	BehavioralRules    pgtype.Text `json:"behavioral_rules"`
	ToolInstructions   pgtype.Text `json:"tool_instructions"`
	IdleTimeoutSeconds pgtype.Int4 `json:"idle_timeout_seconds"`
	VoicePreset        pgtype.Text `json:"voice_preset"`
	VoiceGender        pgtype.Text `json:"voice_gender"`
	BusinessID         string      `json:"business_id"`
}

func (q *Queries) UpdateAIRules(ctx context.Context, arg UpdateAIRulesParams) (AiRule, error) {
	row := q.db.QueryRow(ctx, updateAIRules,
		arg.AssistantName,
		arg.AvatarModelPath,
		arg.Personality,
		arg.Tone,
		arg.Language,
		arg.BehavioralRules,
		arg.ToolInstructions,
		arg.IdleTimeoutSeconds,
		arg.VoicePreset,
		arg.VoiceGender,
		arg.BusinessID,
	)
	var i AiRule
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.AssistantName,
		&i.AvatarUrl,
		&i.AvatarModelPath,
		&i.Personality,
		&i.Tone,
		&i.Language,
		&i.BehavioralRules,
		&i.ToolInstructions,
		&i.IdleTimeoutSeconds,
		&i.VoicePreset,
		&i.VoiceGender,
	)
	return i, err
}
