// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelAppointment = `-- name: CancelAppointment :one
UPDATE appointments SET status = 'cancelled'
WHERE id = $1 AND business_id = $2
RETURNING id, business_id, product_id, treatment_name, customer_name, customer_phone, starts_at, ends_at, status, created_at
`

type CancelAppointmentParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) CancelAppointment(ctx context.Context, arg CancelAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, cancelAppointment, arg.ID, arg.BusinessID)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ProductID,
		&i.TreatmentName,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (
  id, business_id, product_id, treatment_name, customer_name, customer_phone, starts_at, ends_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, business_id, product_id, treatment_name, customer_name, customer_phone, starts_at, ends_at, status, created_at
`

type CreateAppointmentParams struct {
	ID            string             `json:"id"`
	BusinessID    string             `json:"business_id"`
	ProductID     string             `json:"product_id"`
	TreatmentName string             `json:"treatment_name"`
	CustomerName  string             `json:"customer_name"`
	CustomerPhone string             `json:"customer_phone"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.ID,
		arg.BusinessID,
		arg.ProductID,
		arg.TreatmentName,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ProductID,
		&i.TreatmentName,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAppointment = `-- name: GetAppointment :one
SELECT id, business_id, product_id, treatment_name, customer_name, customer_phone, starts_at, ends_at, status, created_at FROM appointments WHERE id = $1 AND business_id = $2
`

type GetAppointmentParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) GetAppointment(ctx context.Context, arg GetAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointment, arg.ID, arg.BusinessID)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ProductID,
		&i.TreatmentName,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAppointmentsInRange = `-- name: ListActiveAppointmentsInRange :many
SELECT id, business_id, product_id, treatment_name, customer_name, customer_phone, starts_at, ends_at, status, created_at FROM appointments
WHERE business_id = $1
  AND starts_at >= $2
  AND starts_at < $3
  AND status != 'cancelled'
`

type ListActiveAppointmentsInRangeParams struct {
	BusinessID string             `json:"business_id"`
	StartsAt   pgtype.Timestamptz `json:"starts_at"`
	StartsAt_2 pgtype.Timestamptz `json:"starts_at_2"`
}

func (q *Queries) ListActiveAppointmentsInRange(ctx context.Context, arg ListActiveAppointmentsInRangeParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listActiveAppointmentsInRange, arg.BusinessID, arg.StartsAt, arg.StartsAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ProductID,
			&i.TreatmentName,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointments = `-- name: ListAppointments :many
SELECT id, business_id, product_id, treatment_name, customer_name, customer_phone, starts_at, ends_at, status, created_at FROM appointments
WHERE business_id = $1
  AND ($2::timestamptz IS NULL OR starts_at >= $2)
  AND ($3::timestamptz IS NULL OR starts_at < $3)
ORDER BY starts_at
`

type ListAppointmentsParams struct {
	BusinessID   string             `json:"business_id"`
	StartsAfter  pgtype.Timestamptz `json:"starts_after"`
	StartsBefore pgtype.Timestamptz `json:"starts_before"`
}

func (q *Queries) ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointments, arg.BusinessID, arg.StartsAfter, arg.StartsBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Appointment{}
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ProductID,
			&i.TreatmentName,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
