// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogsForTarget = `-- name: CountAuditLogsForTarget :one
SELECT count(*) FROM audit_logs WHERE target_type = $1 AND target_id = $2
`

type CountAuditLogsForTargetParams struct {
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
}

func (q *Queries) CountAuditLogsForTarget(ctx context.Context, arg CountAuditLogsForTargetParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsForTarget, arg.TargetType, arg.TargetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (id, admin_id, action, target_type, target_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, admin_id, action, target_type, target_id, metadata, created_at
`

type CreateAuditLogParams struct {
	ID         string `json:"id"`
	AdminID    string `json:"admin_id"`
	Action     string `json:"action"`
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
	Metadata   []byte `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ID,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.admin_id, a.action, a.target_type, a.target_id, a.metadata, a.created_at, p.name AS admin_name, p.email AS admin_email
FROM audit_logs a
JOIN platform_admins p ON p.id = a.admin_id
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAuditLogsRow struct {
	ID         string             `json:"id"`
	AdminID    string             `json:"admin_id"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   string             `json:"target_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	AdminName  string             `json:"admin_name"`
	AdminEmail string             `json:"admin_email"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
			&i.AdminName,
			&i.AdminEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsForTarget = `-- name: ListAuditLogsForTarget :many
SELECT a.id, a.admin_id, a.action, a.target_type, a.target_id, a.metadata, a.created_at, p.name AS admin_name, p.email AS admin_email
FROM audit_logs a
JOIN platform_admins p ON p.id = a.admin_id
WHERE a.target_type = $1 AND a.target_id = $2
ORDER BY a.created_at DESC
LIMIT $3 OFFSET $4
`

type ListAuditLogsForTargetParams struct {
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

type ListAuditLogsForTargetRow struct {
	ID         string             `json:"id"`
	AdminID    string             `json:"admin_id"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   string             `json:"target_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	AdminName  string             `json:"admin_name"`
	AdminEmail string             `json:"admin_email"`
}

func (q *Queries) ListAuditLogsForTarget(ctx context.Context, arg ListAuditLogsForTargetParams) ([]ListAuditLogsForTargetRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsForTarget,
		arg.TargetType,
		arg.TargetID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsForTargetRow{}
	for rows.Next() {
		var i ListAuditLogsForTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
			&i.AdminName,
			&i.AdminEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
