// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: businesses.sql

package store

import (
	"context"
)

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (id, slug, name)
VALUES ($1, $2, $3)
RETURNING id, slug, name, tagline, voice_name, gemini_model, payment_qr_url, background_url, gradient_color, display_orientation, business_type, primary_use_case, onboarding_completed, is_active, created_at
`

type CreateBusinessParams struct {
	ID   string `json:"id"`
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusiness, arg.ID, arg.Slug, arg.Name)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tagline,
		&i.VoiceName,
		&i.GeminiModel,
		&i.PaymentQrUrl,
		&i.BackgroundUrl,
		&i.GradientColor,
		&i.DisplayOrientation,
		&i.BusinessType,
		&i.PrimaryUseCase,
		&i.OnboardingCompleted,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getBusinessByID = `-- name: GetBusinessByID :one
SELECT id, slug, name, tagline, voice_name, gemini_model, payment_qr_url, background_url, gradient_color, display_orientation, business_type, primary_use_case, onboarding_completed, is_active, created_at FROM businesses WHERE id = $1
`

func (q *Queries) GetBusinessByID(ctx context.Context, id string) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessByID, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tagline,
		&i.VoiceName,
		&i.GeminiModel,
		&i.PaymentQrUrl,
		&i.BackgroundUrl,
		&i.GradientColor,
		&i.DisplayOrientation,
		&i.BusinessType,
		&i.PrimaryUseCase,
		&i.OnboardingCompleted,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getBusinessBySlug = `-- name: GetBusinessBySlug :one
SELECT id, slug, name, tagline, voice_name, gemini_model, payment_qr_url, background_url, gradient_color, display_orientation, business_type, primary_use_case, onboarding_completed, is_active, created_at FROM businesses WHERE slug = $1
`

func (q *Queries) GetBusinessBySlug(ctx context.Context, slug string) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessBySlug, slug)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tagline,
		&i.VoiceName,
		&i.GeminiModel,
		&i.PaymentQrUrl,
		&i.BackgroundUrl,
		&i.GradientColor,
		&i.DisplayOrientation,
		&i.BusinessType,
		&i.PrimaryUseCase,
		&i.OnboardingCompleted,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
