// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: business_hours.sql

package store

import (
	"context"
)

const createBusinessHour = `-- name: CreateBusinessHour :one
INSERT INTO business_hours (id, business_id, day_of_week, open_time, close_time, is_closed)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, day_of_week, open_time, close_time, is_closed
`

type CreateBusinessHourParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
	DayOfWeek  int32  `json:"day_of_week"`
	OpenTime   string `json:"open_time"`
	CloseTime  string `json:"close_time"`
	IsClosed   bool   `json:"is_closed"`
}

func (q *Queries) CreateBusinessHour(ctx context.Context, arg CreateBusinessHourParams) (BusinessHour, error) {
	row := q.db.QueryRow(ctx, createBusinessHour,
		arg.ID,
		arg.BusinessID,
		arg.DayOfWeek,
		arg.OpenTime,
		arg.CloseTime,
		arg.IsClosed,
	)
	var i BusinessHour
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.DayOfWeek,
		&i.OpenTime,
		&i.CloseTime,
		&i.IsClosed,
	)
	return i, err
}

const deleteBusinessHours = `-- name: DeleteBusinessHours :exec
DELETE FROM business_hours WHERE business_id = $1
`

func (q *Queries) DeleteBusinessHours(ctx context.Context, businessID string) error {
	_, err := q.db.Exec(ctx, deleteBusinessHours, businessID)
	return err
}

const listBusinessHours = `-- name: ListBusinessHours :many
SELECT id, business_id, day_of_week, open_time, close_time, is_closed FROM business_hours WHERE business_id = $1 ORDER BY day_of_week
`

func (q *Queries) ListBusinessHours(ctx context.Context, businessID string) ([]BusinessHour, error) {
	rows, err := q.db.Query(ctx, listBusinessHours, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessHour{}
	for rows.Next() {
		var i BusinessHour
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.DayOfWeek,
			&i.OpenTime,
			&i.CloseTime,
			&i.IsClosed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
