// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: business_members.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkBusinessMembership = `-- name: CheckBusinessMembership :one
SELECT bm.role
FROM business_members bm
JOIN businesses b ON b.id = bm.business_id
WHERE bm.user_id = $1 AND bm.business_id = $2
`

type CheckBusinessMembershipParams struct {
	UserID     string `json:"user_id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) CheckBusinessMembership(ctx context.Context, arg CheckBusinessMembershipParams) (string, error) {
	row := q.db.QueryRow(ctx, checkBusinessMembership, arg.UserID, arg.BusinessID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const createBusinessMember = `-- name: CreateBusinessMember :one
INSERT INTO business_members (id, user_id, business_id, role)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, business_id, role
`

type CreateBusinessMemberParams struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	BusinessID string `json:"business_id"`
	Role       string `json:"role"`
}

func (q *Queries) CreateBusinessMember(ctx context.Context, arg CreateBusinessMemberParams) (BusinessMember, error) {
	row := q.db.QueryRow(ctx, createBusinessMember,
		arg.ID,
		arg.UserID,
		arg.BusinessID,
		arg.Role,
	)
	var i BusinessMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessID,
		&i.Role,
	)
	return i, err
}

const listBusinessesForUser = `-- name: ListBusinessesForUser :many
SELECT b.id, b.slug, b.name, b.tagline, b.voice_name, b.gemini_model, b.payment_qr_url, b.background_url, b.gradient_color, b.display_orientation, b.business_type, b.primary_use_case, b.onboarding_completed, b.is_active, b.created_at, bm.role
FROM businesses b
JOIN business_members bm ON bm.business_id = b.id
WHERE bm.user_id = $1
ORDER BY b.created_at DESC
`

type ListBusinessesForUserRow struct {
	ID                  string             `json:"id"`
	Slug                string             `json:"slug"`
	Name                string             `json:"name"`
	Tagline             string             `json:"tagline"`
	VoiceName           string             `json:"voice_name"`
	GeminiModel         string             `json:"gemini_model"`
	PaymentQrUrl        string             `json:"payment_qr_url"`
	BackgroundUrl       string             `json:"background_url"`
	GradientColor       string             `json:"gradient_color"`
	DisplayOrientation  string             `json:"display_orientation"`
	BusinessType        string             `json:"business_type"`
	PrimaryUseCase      string             `json:"primary_use_case"`
	OnboardingCompleted bool               `json:"onboarding_completed"`
	IsActive            bool               `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	Role                string             `json:"role"`
}

func (q *Queries) ListBusinessesForUser(ctx context.Context, userID string) ([]ListBusinessesForUserRow, error) {
	rows, err := q.db.Query(ctx, listBusinessesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBusinessesForUserRow{}
	for rows.Next() {
		var i ListBusinessesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Tagline,
			&i.VoiceName,
			&i.GeminiModel,
			&i.PaymentQrUrl,
			&i.BackgroundUrl,
			&i.GradientColor,
			&i.DisplayOrientation,
			&i.BusinessType,
			&i.PrimaryUseCase,
			&i.OnboardingCompleted,
			&i.IsActive,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
