// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledge_entries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKnowledgeEntry = `-- name: CreateKnowledgeEntry :one
INSERT INTO knowledge_entries (id, business_id, category, title, content, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, category, title, content, sort_order
`

type CreateKnowledgeEntryParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
	Category   string `json:"category"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	SortOrder  int32  `json:"sort_order"`
}

func (q *Queries) CreateKnowledgeEntry(ctx context.Context, arg CreateKnowledgeEntryParams) (KnowledgeEntry, error) {
	row := q.db.QueryRow(ctx, createKnowledgeEntry,
		arg.ID,
		arg.BusinessID,
		arg.Category,
		arg.Title,
		arg.Content,
		arg.SortOrder,
	)
	var i KnowledgeEntry
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.SortOrder,
	)
	return i, err
}

const deleteAllKnowledgeEntries = `-- name: DeleteAllKnowledgeEntries :execrows
DELETE FROM knowledge_entries WHERE business_id = $1
`

func (q *Queries) DeleteAllKnowledgeEntries(ctx context.Context, businessID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllKnowledgeEntries, businessID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteKnowledgeEntry = `-- name: DeleteKnowledgeEntry :execrows
DELETE FROM knowledge_entries WHERE id = $1 AND business_id = $2
`

type DeleteKnowledgeEntryParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) DeleteKnowledgeEntry(ctx context.Context, arg DeleteKnowledgeEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteKnowledgeEntry, arg.ID, arg.BusinessID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listKnowledgeEntries = `-- name: ListKnowledgeEntries :many
SELECT id, business_id, category, title, content, sort_order FROM knowledge_entries WHERE business_id = $1 ORDER BY sort_order, category
`

func (q *Queries) ListKnowledgeEntries(ctx context.Context, businessID string) ([]KnowledgeEntry, error) {
	rows, err := q.db.Query(ctx, listKnowledgeEntries, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeEntry{}
	for rows.Next() {
		var i KnowledgeEntry
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Category,
			&i.Title,
			&i.Content,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKnowledgeEntry = `-- name: UpdateKnowledgeEntry :one
UPDATE knowledge_entries SET
  category = COALESCE($1, category),
  title = COALESCE($2, title),
  content = COALESCE($3, content),
  sort_order = COALESCE($4, sort_order)
WHERE id = $5 AND business_id = $6
RETURNING id, business_id, category, title, content, sort_order
`

type UpdateKnowledgeEntryParams struct {
	Category   pgtype.Text `json:"category"`
	Title      pgtype.Text `json:"title"`
	Content    pgtype.Text `json:"content"`
	SortOrder  pgtype.Int4 `json:"sort_order"`
	ID         string      `json:"id"`
	BusinessID string      `json:"business_id"`
}

func (q *Queries) UpdateKnowledgeEntry(ctx context.Context, arg UpdateKnowledgeEntryParams) (KnowledgeEntry, error) {
	row := q.db.QueryRow(ctx, updateKnowledgeEntry,
		arg.Category,
		arg.Title,
		arg.Content,
		arg.SortOrder,
		arg.ID,
		arg.BusinessID,
	)
	var i KnowledgeEntry
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Category,
		&i.Title,
		&i.Content,
		&i.SortOrder,
	)
	return i, err
}
