// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AiRule struct {
	ID                 string `json:"id"`
	BusinessID         string `json:"business_id"`
	AssistantName      string `json:"assistant_name"`
	AvatarUrl          string `json:"avatar_url"`
	AvatarModelPath    string `json:"avatar_model_path"`
	Personality        string `json:"personality"`
	Tone               string `json:"tone"`
	Language           string `json:"language"`
	BehavioralRules    string `json:"behavioral_rules"`
	ToolInstructions   string `json:"tool_instructions"`
	IdleTimeoutSeconds int32  `json:"idle_timeout_seconds"`
	VoicePreset        string `json:"voice_preset"`
	VoiceGender        string `json:"voice_gender"`
}

type Appointment struct {
	ID            string             `json:"id"`
	BusinessID    string             `json:"business_id"`
	ProductID     string             `json:"product_id"`
	TreatmentName string             `json:"treatment_name"`
	CustomerName  string             `json:"customer_name"`
	CustomerPhone string             `json:"customer_phone"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID         string             `json:"id"`
	AdminID    string             `json:"admin_id"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   string             `json:"target_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Business struct {
	ID                  string             `json:"id"`
	Slug                string             `json:"slug"`
	Name                string             `json:"name"`
	Tagline             string             `json:"tagline"`
	VoiceName           string             `json:"voice_name"`
	GeminiModel         string             `json:"gemini_model"`
	PaymentQrUrl        string             `json:"payment_qr_url"`
	BackgroundUrl       string             `json:"background_url"`
	GradientColor       string             `json:"gradient_color"`
	DisplayOrientation  string             `json:"display_orientation"`
	BusinessType        string             `json:"business_type"`
	PrimaryUseCase      string             `json:"primary_use_case"`
	OnboardingCompleted bool               `json:"onboarding_completed"`
	IsActive            bool               `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type BusinessHour struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
	DayOfWeek  int32  `json:"day_of_week"`
	OpenTime   string `json:"open_time"`
	CloseTime  string `json:"close_time"`
	IsClosed   bool   `json:"is_closed"`
}

type BusinessMember struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	BusinessID string `json:"business_id"`
	Role       string `json:"role"`
}

type KnowledgeEntry struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
	Category   string `json:"category"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	SortOrder  int32  `json:"sort_order"`
}

type Order struct {
	ID             string             `json:"id"`
	BusinessID     string             `json:"business_id"`
	VoiceSessionID pgtype.Text        `json:"voice_session_id"`
	Status         string             `json:"status"`
	Total          float64            `json:"total"`
	CustomerName   pgtype.Text        `json:"customer_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ConfirmedAt    pgtype.Timestamptz `json:"confirmed_at"`
}

type OrderItem struct {
	ID        string  `json:"id"`
	OrderID   string  `json:"order_id"`
	ProductID string  `json:"product_id"`
	Name      string  `json:"name"`
	Price     float64 `json:"price"`
	Quantity  int32   `json:"quantity"`
}

type PhotoSession struct {
	ID                string             `json:"id"`
	BusinessID        string             `json:"business_id"`
	OrderID           pgtype.Text        `json:"order_id"`
	VisitorResponse   pgtype.Text        `json:"visitor_response"`
	Status            string             `json:"status"`
	PhotoPath         pgtype.Text        `json:"photo_path"`
	ThumbnailPath     pgtype.Text        `json:"thumbnail_path"`
	QrToken           pgtype.Text        `json:"qr_token"`
	DownloadExpiresAt pgtype.Timestamptz `json:"download_expires_at"`
	DownloadedAt      pgtype.Timestamptz `json:"downloaded_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type PhotoSetting struct {
	BusinessID       string             `json:"business_id"`
	Enabled          bool               `json:"enabled"`
	VoicePrompt      string             `json:"voice_prompt"`
	CountdownSeconds int32              `json:"countdown_seconds"`
	QrExpiryHours    int32              `json:"qr_expiry_hours"`
	LogoUrl          pgtype.Text        `json:"logo_url"`
	FrameUrl         pgtype.Text        `json:"frame_url"`
	CampaignText     pgtype.Text        `json:"campaign_text"`
	AutoDeleteDays   int32              `json:"auto_delete_days"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PlatformAdmin struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	TotpSecret   pgtype.Text        `json:"totp_secret"`
	TotpEnabled  bool               `json:"totp_enabled"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Presentation struct {
	ID                string             `json:"id"`
	BusinessID        string             `json:"business_id"`
	CreatedBy         pgtype.Text        `json:"created_by"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	Language          string             `json:"language"`
	Category          string             `json:"category"`
	Status            string             `json:"status"`
	ProcessingStep    string             `json:"processing_step"`
	ProcessingError   string             `json:"processing_error"`
	TotalSlides       int32              `json:"total_slides"`
	EstimatedDuration int32              `json:"estimated_duration"`
	GreetingScript    string             `json:"greeting_script"`
	ClosingScript     string             `json:"closing_script"`
	ThumbnailUrl      string             `json:"thumbnail_url"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type PresentationAudioAsset struct {
	ID              string             `json:"id"`
	SlideID         string             `json:"slide_id"`
	Kind            string             `json:"kind"`
	Provider        string             `json:"provider"`
	StoragePath     string             `json:"storage_path"`
	DurationSeconds int32              `json:"duration_seconds"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PresentationEmbedding struct {
	ID                 string             `json:"id"`
	PresentationID     string             `json:"presentation_id"`
	SourceType         string             `json:"source_type"`
	SourceID           pgtype.Text        `json:"source_id"`
	ChunkText          string             `json:"chunk_text"`
	EmbeddingReference string             `json:"embedding_reference"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type PresentationFile struct {
	ID             string             `json:"id"`
	PresentationID string             `json:"presentation_id"`
	FileName       string             `json:"file_name"`
	FileType       string             `json:"file_type"`
	SizeBytes      int32              `json:"size_bytes"`
	StoragePath    string             `json:"storage_path"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PresentationKnowledgeEntry struct {
	ID             string             `json:"id"`
	PresentationID string             `json:"presentation_id"`
	Title          string             `json:"title"`
	Content        string             `json:"content"`
	SortOrder      int32              `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PresentationQuestion struct {
	ID               string             `json:"id"`
	SessionID        string             `json:"session_id"`
	Question         string             `json:"question"`
	Answer           string             `json:"answer"`
	Status           string             `json:"status"`
	ModerationResult string             `json:"moderation_result"`
	SourceReferences string             `json:"source_references"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	AnsweredAt       pgtype.Timestamptz `json:"answered_at"`
}

type PresentationSession struct {
	ID                 string             `json:"id"`
	PresentationID     string             `json:"presentation_id"`
	BusinessID         string             `json:"business_id"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	CurrentSlideNumber int32              `json:"current_slide_number"`
	EnableQna          bool               `json:"enable_qna"`
	AutoStart          bool               `json:"auto_start"`
	AudienceCount      int32              `json:"audience_count"`
	QuestionCount      int32              `json:"question_count"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type PresentationSlide struct {
	ID              string             `json:"id"`
	PresentationID  string             `json:"presentation_id"`
	SlideNumber     int32              `json:"slide_number"`
	Title           string             `json:"title"`
	ContentJson     string             `json:"content_json"`
	Notes           string             `json:"notes"`
	Script          string             `json:"script"`
	ImageUrl        string             `json:"image_url"`
	DurationSeconds int32              `json:"duration_seconds"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID              string  `json:"id"`
	BusinessID      string  `json:"business_id"`
	ProductID       string  `json:"product_id"`
	Name            string  `json:"name"`
	Price           float64 `json:"price"`
	DiscountPercent float64 `json:"discount_percent"`
	Category        string  `json:"category"`
	Description     string  `json:"description"`
	ImageUrl        string  `json:"image_url"`
	IsActive        bool    `json:"is_active"`
	SortOrder       int32   `json:"sort_order"`
	DurationMin     int32   `json:"duration_min"`
}

type TranscriptMessage struct {
	ID             string             `json:"id"`
	VoiceSessionID string             `json:"voice_session_id"`
	Role           string             `json:"role"`
	Text           string             `json:"text"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type UsageEvent struct {
	ID         string             `json:"id"`
	BusinessID string             `json:"business_id"`
	EventType  string             `json:"event_type"`
	Quantity   pgtype.Numeric     `json:"quantity"`
	Metadata   []byte             `json:"metadata"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type User struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	Phone        string             `json:"phone"`
	Country      string             `json:"country"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type VoiceSession struct {
	ID         string             `json:"id"`
	BusinessID string             `json:"business_id"`
	Status     string             `json:"status"`
	EndReason  pgtype.Text        `json:"end_reason"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	EndedAt    pgtype.Timestamptz `json:"ended_at"`
}
