// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, business_id, voice_session_id, status, total, confirmed_at)
VALUES ($1, $2, $3, 'confirmed', $4, NOW())
RETURNING id, business_id, voice_session_id, status, total, customer_name, created_at, confirmed_at
`

type CreateOrderParams struct {
	ID             string      `json:"id"`
	BusinessID     string      `json:"business_id"`
	VoiceSessionID pgtype.Text `json:"voice_session_id"`
	Total          float64     `json:"total"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.BusinessID,
		arg.VoiceSessionID,
		arg.Total,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.VoiceSessionID,
		&i.Status,
		&i.Total,
		&i.CustomerName,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (id, order_id, product_id, name, price, quantity)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, product_id, name, price, quantity
`

type CreateOrderItemParams struct {
	ID        string  `json:"id"`
	OrderID   string  `json:"order_id"`
	ProductID string  `json:"product_id"`
	Name      string  `json:"name"`
	Price     float64 `json:"price"`
	Quantity  int32   `json:"quantity"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.Name,
		arg.Price,
		arg.Quantity,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Name,
		&i.Price,
		&i.Quantity,
	)
	return i, err
}

const getMostRecentOrderForVoiceSession = `-- name: GetMostRecentOrderForVoiceSession :one
SELECT id, business_id, voice_session_id, status, total, customer_name, created_at, confirmed_at FROM orders
WHERE voice_session_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetMostRecentOrderForVoiceSession(ctx context.Context, voiceSessionID pgtype.Text) (Order, error) {
	row := q.db.QueryRow(ctx, getMostRecentOrderForVoiceSession, voiceSessionID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.VoiceSessionID,
		&i.Status,
		&i.Total,
		&i.CustomerName,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const listOrderItemsForOrders = `-- name: ListOrderItemsForOrders :many
SELECT id, order_id, product_id, name, price, quantity FROM order_items WHERE order_id = ANY($1::varchar[])
`

func (q *Queries) ListOrderItemsForOrders(ctx context.Context, orderIds []string) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsForOrders, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Name,
			&i.Price,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersForBusiness = `-- name: ListOrdersForBusiness :many
SELECT id, business_id, voice_session_id, status, total, customer_name, created_at, confirmed_at FROM orders WHERE business_id = $1 ORDER BY created_at DESC LIMIT 200
`

func (q *Queries) ListOrdersForBusiness(ctx context.Context, businessID string) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersForBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.VoiceSessionID,
			&i.Status,
			&i.Total,
			&i.CustomerName,
			&i.CreatedAt,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderCustomerName = `-- name: UpdateOrderCustomerName :one
UPDATE orders SET customer_name = $2
WHERE id = $1
RETURNING id, business_id, voice_session_id, status, total, customer_name, created_at, confirmed_at
`

type UpdateOrderCustomerNameParams struct {
	ID           string      `json:"id"`
	CustomerName pgtype.Text `json:"customer_name"`
}

func (q *Queries) UpdateOrderCustomerName(ctx context.Context, arg UpdateOrderCustomerNameParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderCustomerName, arg.ID, arg.CustomerName)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.VoiceSessionID,
		&i.Status,
		&i.Total,
		&i.CustomerName,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}
