// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photo_settings.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPhotoSettings = `-- name: CreatePhotoSettings :one
INSERT INTO photo_settings (business_id)
VALUES ($1)
ON CONFLICT (business_id) DO UPDATE SET business_id = EXCLUDED.business_id
RETURNING business_id, enabled, voice_prompt, countdown_seconds, qr_expiry_hours, logo_url, frame_url, campaign_text, auto_delete_days, updated_at
`

func (q *Queries) CreatePhotoSettings(ctx context.Context, businessID string) (PhotoSetting, error) {
	row := q.db.QueryRow(ctx, createPhotoSettings, businessID)
	var i PhotoSetting
	err := row.Scan(
		&i.BusinessID,
		&i.Enabled,
		&i.VoicePrompt,
		&i.CountdownSeconds,
		&i.QrExpiryHours,
		&i.LogoUrl,
		&i.FrameUrl,
		&i.CampaignText,
		&i.AutoDeleteDays,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhotoSettings = `-- name: GetPhotoSettings :one
SELECT business_id, enabled, voice_prompt, countdown_seconds, qr_expiry_hours, logo_url, frame_url, campaign_text, auto_delete_days, updated_at FROM photo_settings WHERE business_id = $1
`

func (q *Queries) GetPhotoSettings(ctx context.Context, businessID string) (PhotoSetting, error) {
	row := q.db.QueryRow(ctx, getPhotoSettings, businessID)
	var i PhotoSetting
	err := row.Scan(
		&i.BusinessID,
		&i.Enabled,
		&i.VoicePrompt,
		&i.CountdownSeconds,
		&i.QrExpiryHours,
		&i.LogoUrl,
		&i.FrameUrl,
		&i.CampaignText,
		&i.AutoDeleteDays,
		&i.UpdatedAt,
	)
	return i, err
}

const listPhotoSettingsForCleanup = `-- name: ListPhotoSettingsForCleanup :many
SELECT business_id, enabled, voice_prompt, countdown_seconds, qr_expiry_hours, logo_url, frame_url, campaign_text, auto_delete_days, updated_at FROM photo_settings
`

func (q *Queries) ListPhotoSettingsForCleanup(ctx context.Context) ([]PhotoSetting, error) {
	rows, err := q.db.Query(ctx, listPhotoSettingsForCleanup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PhotoSetting{}
	for rows.Next() {
		var i PhotoSetting
		if err := rows.Scan(
			&i.BusinessID,
			&i.Enabled,
			&i.VoicePrompt,
			&i.CountdownSeconds,
			&i.QrExpiryHours,
			&i.LogoUrl,
			&i.FrameUrl,
			&i.CampaignText,
			&i.AutoDeleteDays,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPhotoFrameURL = `-- name: SetPhotoFrameURL :one
UPDATE photo_settings SET frame_url = $2, updated_at = NOW()
WHERE business_id = $1
RETURNING business_id, enabled, voice_prompt, countdown_seconds, qr_expiry_hours, logo_url, frame_url, campaign_text, auto_delete_days, updated_at
`

type SetPhotoFrameURLParams struct {
	BusinessID string      `json:"business_id"`
	FrameUrl   pgtype.Text `json:"frame_url"`
}

func (q *Queries) SetPhotoFrameURL(ctx context.Context, arg SetPhotoFrameURLParams) (PhotoSetting, error) {
	row := q.db.QueryRow(ctx, setPhotoFrameURL, arg.BusinessID, arg.FrameUrl)
	var i PhotoSetting
	err := row.Scan(
		&i.BusinessID,
		&i.Enabled,
		&i.VoicePrompt,
		&i.CountdownSeconds,
		&i.QrExpiryHours,
		&i.LogoUrl,
		&i.FrameUrl,
		&i.CampaignText,
		&i.AutoDeleteDays,
		&i.UpdatedAt,
	)
	return i, err
}

const setPhotoLogoURL = `-- name: SetPhotoLogoURL :one
UPDATE photo_settings SET logo_url = $2, updated_at = NOW()
WHERE business_id = $1
RETURNING business_id, enabled, voice_prompt, countdown_seconds, qr_expiry_hours, logo_url, frame_url, campaign_text, auto_delete_days, updated_at
`

type SetPhotoLogoURLParams struct {
	BusinessID string      `json:"business_id"`
	LogoUrl    pgtype.Text `json:"logo_url"`
}

func (q *Queries) SetPhotoLogoURL(ctx context.Context, arg SetPhotoLogoURLParams) (PhotoSetting, error) {
	row := q.db.QueryRow(ctx, setPhotoLogoURL, arg.BusinessID, arg.LogoUrl)
	var i PhotoSetting
	err := row.Scan(
		&i.BusinessID,
		&i.Enabled,
		&i.VoicePrompt,
		&i.CountdownSeconds,
		&i.QrExpiryHours,
		&i.LogoUrl,
		&i.FrameUrl,
		&i.CampaignText,
		&i.AutoDeleteDays,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePhotoSettings = `-- name: UpdatePhotoSettings :one
UPDATE photo_settings SET
  enabled = COALESCE($1, enabled),
  voice_prompt = COALESCE($2, voice_prompt),
  countdown_seconds = COALESCE($3, countdown_seconds),
  qr_expiry_hours = COALESCE($4, qr_expiry_hours),
  campaign_text = COALESCE($5, campaign_text),
  auto_delete_days = COALESCE($6, auto_delete_days),
  updated_at = NOW()
WHERE business_id = $7
RETURNING business_id, enabled, voice_prompt, countdown_seconds, qr_expiry_hours, logo_url, frame_url, campaign_text, auto_delete_days, updated_at
`

type UpdatePhotoSettingsParams struct {
	Enabled          pgtype.Bool `json:"enabled"`
	VoicePrompt      pgtype.Text `json:"voice_prompt"`
	CountdownSeconds pgtype.Int4 `json:"countdown_seconds"`
	QrExpiryHours    pgtype.Int4 `json:"qr_expiry_hours"`
	CampaignText     pgtype.Text `json:"campaign_text"`
	AutoDeleteDays   pgtype.Int4 `json:"auto_delete_days"`
	BusinessID       string      `json:"business_id"`
}

func (q *Queries) UpdatePhotoSettings(ctx context.Context, arg UpdatePhotoSettingsParams) (PhotoSetting, error) {
	row := q.db.QueryRow(ctx, updatePhotoSettings,
		arg.Enabled,
		arg.VoicePrompt,
		arg.CountdownSeconds,
		arg.QrExpiryHours,
		arg.CampaignText,
		arg.AutoDeleteDays,
		arg.BusinessID,
	)
	var i PhotoSetting
	err := row.Scan(
		&i.BusinessID,
		&i.Enabled,
		&i.VoicePrompt,
		&i.CountdownSeconds,
		&i.QrExpiryHours,
		&i.LogoUrl,
		&i.FrameUrl,
		&i.CampaignText,
		&i.AutoDeleteDays,
		&i.UpdatedAt,
	)
	return i, err
}
