// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photo_sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completePhotoSession = `-- name: CompletePhotoSession :one
UPDATE photo_sessions SET
  qr_token = COALESCE(qr_token, $2),
  download_expires_at = $3,
  status = 'completed'
WHERE id = $1
RETURNING id, business_id, order_id, visitor_response, status, photo_path, thumbnail_path, qr_token, download_expires_at, downloaded_at, created_at
`

type CompletePhotoSessionParams struct {
	ID                string             `json:"id"`
	QrToken           pgtype.Text        `json:"qr_token"`
	DownloadExpiresAt pgtype.Timestamptz `json:"download_expires_at"`
}

func (q *Queries) CompletePhotoSession(ctx context.Context, arg CompletePhotoSessionParams) (PhotoSession, error) {
	row := q.db.QueryRow(ctx, completePhotoSession, arg.ID, arg.QrToken, arg.DownloadExpiresAt)
	var i PhotoSession
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OrderID,
		&i.VisitorResponse,
		&i.Status,
		&i.PhotoPath,
		&i.ThumbnailPath,
		&i.QrToken,
		&i.DownloadExpiresAt,
		&i.DownloadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPhotoSession = `-- name: CreatePhotoSession :one
INSERT INTO photo_sessions (id, business_id, order_id, status)
VALUES ($1, $2, $3, 'started')
RETURNING id, business_id, order_id, visitor_response, status, photo_path, thumbnail_path, qr_token, download_expires_at, downloaded_at, created_at
`

type CreatePhotoSessionParams struct {
	ID         string      `json:"id"`
	BusinessID string      `json:"business_id"`
	OrderID    pgtype.Text `json:"order_id"`
}

func (q *Queries) CreatePhotoSession(ctx context.Context, arg CreatePhotoSessionParams) (PhotoSession, error) {
	row := q.db.QueryRow(ctx, createPhotoSession, arg.ID, arg.BusinessID, arg.OrderID)
	var i PhotoSession
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OrderID,
		&i.VisitorResponse,
		&i.Status,
		&i.PhotoPath,
		&i.ThumbnailPath,
		&i.QrToken,
		&i.DownloadExpiresAt,
		&i.DownloadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePhotoSession = `-- name: DeletePhotoSession :one
DELETE FROM photo_sessions WHERE id = $1 AND business_id = $2
RETURNING id, business_id, order_id, visitor_response, status, photo_path, thumbnail_path, qr_token, download_expires_at, downloaded_at, created_at
`

type DeletePhotoSessionParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) DeletePhotoSession(ctx context.Context, arg DeletePhotoSessionParams) (PhotoSession, error) {
	row := q.db.QueryRow(ctx, deletePhotoSession, arg.ID, arg.BusinessID)
	var i PhotoSession
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OrderID,
		&i.VisitorResponse,
		&i.Status,
		&i.PhotoPath,
		&i.ThumbnailPath,
		&i.QrToken,
		&i.DownloadExpiresAt,
		&i.DownloadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePhotoSessionByID = `-- name: DeletePhotoSessionByID :exec
DELETE FROM photo_sessions WHERE id = $1
`

func (q *Queries) DeletePhotoSessionByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePhotoSessionByID, id)
	return err
}

const expireQrTokens = `-- name: ExpireQrTokens :execrows
UPDATE photo_sessions SET status = 'expired'
WHERE status = 'completed' AND download_expires_at IS NOT NULL AND download_expires_at < NOW()
`

func (q *Queries) ExpireQrTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireQrTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPhotoSession = `-- name: GetPhotoSession :one
SELECT id, business_id, order_id, visitor_response, status, photo_path, thumbnail_path, qr_token, download_expires_at, downloaded_at, created_at FROM photo_sessions WHERE id = $1 AND business_id = $2
`

type GetPhotoSessionParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) GetPhotoSession(ctx context.Context, arg GetPhotoSessionParams) (PhotoSession, error) {
	row := q.db.QueryRow(ctx, getPhotoSession, arg.ID, arg.BusinessID)
	var i PhotoSession
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OrderID,
		&i.VisitorResponse,
		&i.Status,
		&i.PhotoPath,
		&i.ThumbnailPath,
		&i.QrToken,
		&i.DownloadExpiresAt,
		&i.DownloadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPhotoSessionByToken = `-- name: GetPhotoSessionByToken :one
SELECT id, business_id, order_id, visitor_response, status, photo_path, thumbnail_path, qr_token, download_expires_at, downloaded_at, created_at FROM photo_sessions WHERE qr_token = $1
`

func (q *Queries) GetPhotoSessionByToken(ctx context.Context, qrToken pgtype.Text) (PhotoSession, error) {
	row := q.db.QueryRow(ctx, getPhotoSessionByToken, qrToken)
	var i PhotoSession
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OrderID,
		&i.VisitorResponse,
		&i.Status,
		&i.PhotoPath,
		&i.ThumbnailPath,
		&i.QrToken,
		&i.DownloadExpiresAt,
		&i.DownloadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listExpiredPhotoSessionsForBusiness = `-- name: ListExpiredPhotoSessionsForBusiness :many
SELECT id, business_id, order_id, visitor_response, status, photo_path, thumbnail_path, qr_token, download_expires_at, downloaded_at, created_at FROM photo_sessions WHERE business_id = $1 AND created_at < $2
`

type ListExpiredPhotoSessionsForBusinessParams struct {
	BusinessID string             `json:"business_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListExpiredPhotoSessionsForBusiness(ctx context.Context, arg ListExpiredPhotoSessionsForBusinessParams) ([]PhotoSession, error) {
	rows, err := q.db.Query(ctx, listExpiredPhotoSessionsForBusiness, arg.BusinessID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PhotoSession{}
	for rows.Next() {
		var i PhotoSession
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.OrderID,
			&i.VisitorResponse,
			&i.Status,
			&i.PhotoPath,
			&i.ThumbnailPath,
			&i.QrToken,
			&i.DownloadExpiresAt,
			&i.DownloadedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotoGalleryForBusiness = `-- name: ListPhotoGalleryForBusiness :many
SELECT id, business_id, order_id, visitor_response, status, photo_path, thumbnail_path, qr_token, download_expires_at, downloaded_at, created_at FROM photo_sessions
WHERE business_id = $1 AND photo_path IS NOT NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPhotoGalleryForBusinessParams struct {
	BusinessID string `json:"business_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListPhotoGalleryForBusiness(ctx context.Context, arg ListPhotoGalleryForBusinessParams) ([]PhotoSession, error) {
	rows, err := q.db.Query(ctx, listPhotoGalleryForBusiness, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PhotoSession{}
	for rows.Next() {
		var i PhotoSession
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.OrderID,
			&i.VisitorResponse,
			&i.Status,
			&i.PhotoPath,
			&i.ThumbnailPath,
			&i.QrToken,
			&i.DownloadExpiresAt,
			&i.DownloadedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPhotoSessionDownloaded = `-- name: MarkPhotoSessionDownloaded :one
UPDATE photo_sessions SET downloaded_at = NOW()
WHERE id = $1 AND downloaded_at IS NULL
RETURNING id, business_id, order_id, visitor_response, status, photo_path, thumbnail_path, qr_token, download_expires_at, downloaded_at, created_at
`

func (q *Queries) MarkPhotoSessionDownloaded(ctx context.Context, id string) (PhotoSession, error) {
	row := q.db.QueryRow(ctx, markPhotoSessionDownloaded, id)
	var i PhotoSession
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OrderID,
		&i.VisitorResponse,
		&i.Status,
		&i.PhotoPath,
		&i.ThumbnailPath,
		&i.QrToken,
		&i.DownloadExpiresAt,
		&i.DownloadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setPhotoSessionResponse = `-- name: SetPhotoSessionResponse :one
UPDATE photo_sessions SET visitor_response = $2, status = $3
WHERE id = $1
RETURNING id, business_id, order_id, visitor_response, status, photo_path, thumbnail_path, qr_token, download_expires_at, downloaded_at, created_at
`

type SetPhotoSessionResponseParams struct {
	ID              string      `json:"id"`
	VisitorResponse pgtype.Text `json:"visitor_response"`
	Status          string      `json:"status"`
}

func (q *Queries) SetPhotoSessionResponse(ctx context.Context, arg SetPhotoSessionResponseParams) (PhotoSession, error) {
	row := q.db.QueryRow(ctx, setPhotoSessionResponse, arg.ID, arg.VisitorResponse, arg.Status)
	var i PhotoSession
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OrderID,
		&i.VisitorResponse,
		&i.Status,
		&i.PhotoPath,
		&i.ThumbnailPath,
		&i.QrToken,
		&i.DownloadExpiresAt,
		&i.DownloadedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setPhotoSessionUpload = `-- name: SetPhotoSessionUpload :one
UPDATE photo_sessions SET photo_path = $2, thumbnail_path = $3, status = 'captured'
WHERE id = $1
RETURNING id, business_id, order_id, visitor_response, status, photo_path, thumbnail_path, qr_token, download_expires_at, downloaded_at, created_at
`

type SetPhotoSessionUploadParams struct {
	ID            string      `json:"id"`
	PhotoPath     pgtype.Text `json:"photo_path"`
	ThumbnailPath pgtype.Text `json:"thumbnail_path"`
}

func (q *Queries) SetPhotoSessionUpload(ctx context.Context, arg SetPhotoSessionUploadParams) (PhotoSession, error) {
	row := q.db.QueryRow(ctx, setPhotoSessionUpload, arg.ID, arg.PhotoPath, arg.ThumbnailPath)
	var i PhotoSession
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.OrderID,
		&i.VisitorResponse,
		&i.Status,
		&i.PhotoPath,
		&i.ThumbnailPath,
		&i.QrToken,
		&i.DownloadExpiresAt,
		&i.DownloadedAt,
		&i.CreatedAt,
	)
	return i, err
}
