// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_businesses.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveBusinesses = `-- name: CountActiveBusinesses :one
SELECT count(*) FROM businesses WHERE is_active = TRUE
`

func (q *Queries) CountActiveBusinesses(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBusinesses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBusinessesForPlatform = `-- name: CountBusinessesForPlatform :one
SELECT count(*) FROM businesses
WHERE $1::text IS NULL
   OR name ILIKE '%' || $1::text || '%'
   OR slug ILIKE '%' || $1::text || '%'
`

func (q *Queries) CountBusinessesForPlatform(ctx context.Context, search pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countBusinessesForPlatform, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBusinessMemberCount = `-- name: GetBusinessMemberCount :one
SELECT count(*) FROM business_members WHERE business_id = $1
`

func (q *Queries) GetBusinessMemberCount(ctx context.Context, businessID string) (int64, error) {
	row := q.db.QueryRow(ctx, getBusinessMemberCount, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBusinessOwnerUserID = `-- name: GetBusinessOwnerUserID :one
SELECT bm.user_id
FROM business_members bm
WHERE bm.business_id = $1
ORDER BY (bm.role = 'owner') DESC, bm.id
LIMIT 1
`

func (q *Queries) GetBusinessOwnerUserID(ctx context.Context, businessID string) (string, error) {
	row := q.db.QueryRow(ctx, getBusinessOwnerUserID, businessID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getBusinessPresentationCount = `-- name: GetBusinessPresentationCount :one
SELECT count(*) FROM presentations WHERE business_id = $1
`

func (q *Queries) GetBusinessPresentationCount(ctx context.Context, businessID string) (int64, error) {
	row := q.db.QueryRow(ctx, getBusinessPresentationCount, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBusinessProductCount = `-- name: GetBusinessProductCount :one
SELECT count(*) FROM products WHERE business_id = $1
`

func (q *Queries) GetBusinessProductCount(ctx context.Context, businessID string) (int64, error) {
	row := q.db.QueryRow(ctx, getBusinessProductCount, businessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasAIRulesConfigured = `-- name: HasAIRulesConfigured :one
SELECT EXISTS(SELECT 1 FROM ai_rules WHERE business_id = $1)
`

func (q *Queries) HasAIRulesConfigured(ctx context.Context, businessID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasAIRulesConfigured, businessID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBusinessMembersForPlatform = `-- name: ListBusinessMembersForPlatform :many
SELECT bm.role, u.id AS user_id, u.email, u.name
FROM business_members bm
JOIN users u ON u.id = bm.user_id
WHERE bm.business_id = $1
ORDER BY bm.id
`

type ListBusinessMembersForPlatformRow struct {
	Role   string `json:"role"`
	UserID string `json:"user_id"`
	Email  string `json:"email"`
	Name   string `json:"name"`
}

func (q *Queries) ListBusinessMembersForPlatform(ctx context.Context, businessID string) ([]ListBusinessMembersForPlatformRow, error) {
	rows, err := q.db.Query(ctx, listBusinessMembersForPlatform, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBusinessMembersForPlatformRow{}
	for rows.Next() {
		var i ListBusinessMembersForPlatformRow
		if err := rows.Scan(
			&i.Role,
			&i.UserID,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinessesForPlatform = `-- name: ListBusinessesForPlatform :many
SELECT id, slug, name, tagline, voice_name, gemini_model, payment_qr_url, background_url, gradient_color, display_orientation, business_type, primary_use_case, onboarding_completed, is_active, created_at FROM businesses
WHERE $3::text IS NULL
   OR name ILIKE '%' || $3::text || '%'
   OR slug ILIKE '%' || $3::text || '%'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBusinessesForPlatformParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) ListBusinessesForPlatform(ctx context.Context, arg ListBusinessesForPlatformParams) ([]Business, error) {
	rows, err := q.db.Query(ctx, listBusinessesForPlatform, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Tagline,
			&i.VoiceName,
			&i.GeminiModel,
			&i.PaymentQrUrl,
			&i.BackgroundUrl,
			&i.GradientColor,
			&i.DisplayOrientation,
			&i.BusinessType,
			&i.PrimaryUseCase,
			&i.OnboardingCompleted,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBusinessStatus = `-- name: UpdateBusinessStatus :one
UPDATE businesses SET is_active = $2 WHERE id = $1
RETURNING id, slug, name, tagline, voice_name, gemini_model, payment_qr_url, background_url, gradient_color, display_orientation, business_type, primary_use_case, onboarding_completed, is_active, created_at
`

type UpdateBusinessStatusParams struct {
	ID       string `json:"id"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) UpdateBusinessStatus(ctx context.Context, arg UpdateBusinessStatusParams) (Business, error) {
	row := q.db.QueryRow(ctx, updateBusinessStatus, arg.ID, arg.IsActive)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Tagline,
		&i.VoiceName,
		&i.GeminiModel,
		&i.PaymentQrUrl,
		&i.BackgroundUrl,
		&i.GradientColor,
		&i.DisplayOrientation,
		&i.BusinessType,
		&i.PrimaryUseCase,
		&i.OnboardingCompleted,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
