// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersByStatus = `-- name: CountUsersByStatus :one
SELECT count(*) FROM users WHERE status = $1
`

func (q *Queries) CountUsersByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersForPlatform = `-- name: CountUsersForPlatform :one
SELECT count(*) FROM users
WHERE $1::text IS NULL
   OR email ILIKE '%' || $1::text || '%'
   OR name ILIKE '%' || $1::text || '%'
`

func (q *Queries) CountUsersForPlatform(ctx context.Context, search pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersForPlatform, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listBusinessMembershipsForUser = `-- name: ListBusinessMembershipsForUser :many
SELECT b.id AS business_id, b.slug, b.name, bm.role
FROM business_members bm
JOIN businesses b ON b.id = bm.business_id
WHERE bm.user_id = $1
ORDER BY b.created_at DESC
`

type ListBusinessMembershipsForUserRow struct {
	BusinessID string `json:"business_id"`
	Slug       string `json:"slug"`
	Name       string `json:"name"`
	Role       string `json:"role"`
}

func (q *Queries) ListBusinessMembershipsForUser(ctx context.Context, userID string) ([]ListBusinessMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listBusinessMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBusinessMembershipsForUserRow{}
	for rows.Next() {
		var i ListBusinessMembershipsForUserRow
		if err := rows.Scan(
			&i.BusinessID,
			&i.Slug,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentUserSignups = `-- name: ListRecentUserSignups :many
SELECT id, email, password_hash, name, status, phone, country, last_login_at, created_at FROM users ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListRecentUserSignups(ctx context.Context, limit int32) ([]User, error) {
	rows, err := q.db.Query(ctx, listRecentUserSignups, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Status,
			&i.Phone,
			&i.Country,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForPlatform = `-- name: ListUsersForPlatform :many
SELECT id, email, password_hash, name, status, phone, country, last_login_at, created_at FROM users
WHERE $3::text IS NULL
   OR email ILIKE '%' || $3::text || '%'
   OR name ILIKE '%' || $3::text || '%'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersForPlatformParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) ListUsersForPlatform(ctx context.Context, arg ListUsersForPlatformParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersForPlatform, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Status,
			&i.Phone,
			&i.Country,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordHashParams struct {
	ID           string `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users SET status = $2 WHERE id = $1
RETURNING id, email, password_hash, name, status, phone, country, last_login_at, created_at
`

type UpdateUserStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.Phone,
		&i.Country,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}
