// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_admins.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlatformAdmins = `-- name: CountPlatformAdmins :one
SELECT count(*) FROM platform_admins
`

func (q *Queries) CountPlatformAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlatformAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlatformAdmin = `-- name: CreatePlatformAdmin :one
INSERT INTO platform_admins (id, name, email, password_hash, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, password_hash, role, status, totp_secret, totp_enabled, last_login_at, created_at
`

type CreatePlatformAdminParams struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) CreatePlatformAdmin(ctx context.Context, arg CreatePlatformAdminParams) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, createPlatformAdmin,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformAdminByEmail = `-- name: GetPlatformAdminByEmail :one
SELECT id, name, email, password_hash, role, status, totp_secret, totp_enabled, last_login_at, created_at FROM platform_admins WHERE email = $1
`

func (q *Queries) GetPlatformAdminByEmail(ctx context.Context, email string) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminByEmail, email)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformAdminByID = `-- name: GetPlatformAdminByID :one
SELECT id, name, email, password_hash, role, status, totp_secret, totp_enabled, last_login_at, created_at FROM platform_admins WHERE id = $1
`

func (q *Queries) GetPlatformAdminByID(ctx context.Context, id string) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminByID, id)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const setPlatformAdminTOTP = `-- name: SetPlatformAdminTOTP :one
UPDATE platform_admins SET totp_secret = $2, totp_enabled = $3
WHERE id = $1
RETURNING id, name, email, password_hash, role, status, totp_secret, totp_enabled, last_login_at, created_at
`

type SetPlatformAdminTOTPParams struct {
	ID          string      `json:"id"`
	TotpSecret  pgtype.Text `json:"totp_secret"`
	TotpEnabled bool        `json:"totp_enabled"`
}

func (q *Queries) SetPlatformAdminTOTP(ctx context.Context, arg SetPlatformAdminTOTPParams) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, setPlatformAdminTOTP, arg.ID, arg.TotpSecret, arg.TotpEnabled)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const updatePlatformAdminLastLogin = `-- name: UpdatePlatformAdminLastLogin :exec
UPDATE platform_admins SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) UpdatePlatformAdminLastLogin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updatePlatformAdminLastLogin, id)
	return err
}

const updatePlatformAdminPasswordHash = `-- name: UpdatePlatformAdminPasswordHash :exec
UPDATE platform_admins SET password_hash = $2 WHERE id = $1
`

type UpdatePlatformAdminPasswordHashParams struct {
	ID           string `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdatePlatformAdminPasswordHash(ctx context.Context, arg UpdatePlatformAdminPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePlatformAdminPasswordHash, arg.ID, arg.PasswordHash)
	return err
}
