// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presentation_embeddings.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPresentationEmbedding = `-- name: CreatePresentationEmbedding :one
INSERT INTO presentation_embeddings (id, presentation_id, source_type, source_id, chunk_text)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, presentation_id, source_type, source_id, chunk_text, embedding_reference, created_at
`

type CreatePresentationEmbeddingParams struct {
	ID             string      `json:"id"`
	PresentationID string      `json:"presentation_id"`
	SourceType     string      `json:"source_type"`
	SourceID       pgtype.Text `json:"source_id"`
	ChunkText      string      `json:"chunk_text"`
}

func (q *Queries) CreatePresentationEmbedding(ctx context.Context, arg CreatePresentationEmbeddingParams) (PresentationEmbedding, error) {
	row := q.db.QueryRow(ctx, createPresentationEmbedding,
		arg.ID,
		arg.PresentationID,
		arg.SourceType,
		arg.SourceID,
		arg.ChunkText,
	)
	var i PresentationEmbedding
	err := row.Scan(
		&i.ID,
		&i.PresentationID,
		&i.SourceType,
		&i.SourceID,
		&i.ChunkText,
		&i.EmbeddingReference,
		&i.CreatedAt,
	)
	return i, err
}

const deleteKnowledgeEmbeddings = `-- name: DeleteKnowledgeEmbeddings :exec
DELETE FROM presentation_embeddings WHERE presentation_id = $1 AND source_type = 'knowledge' AND source_id = $2
`

type DeleteKnowledgeEmbeddingsParams struct {
	PresentationID string      `json:"presentation_id"`
	SourceID       pgtype.Text `json:"source_id"`
}

func (q *Queries) DeleteKnowledgeEmbeddings(ctx context.Context, arg DeleteKnowledgeEmbeddingsParams) error {
	_, err := q.db.Exec(ctx, deleteKnowledgeEmbeddings, arg.PresentationID, arg.SourceID)
	return err
}

const deleteNonKnowledgeEmbeddings = `-- name: DeleteNonKnowledgeEmbeddings :exec
DELETE FROM presentation_embeddings WHERE presentation_id = $1 AND source_type != 'knowledge'
`

func (q *Queries) DeleteNonKnowledgeEmbeddings(ctx context.Context, presentationID string) error {
	_, err := q.db.Exec(ctx, deleteNonKnowledgeEmbeddings, presentationID)
	return err
}

const listPresentationEmbeddings = `-- name: ListPresentationEmbeddings :many
SELECT id, presentation_id, source_type, source_id, chunk_text, embedding_reference, created_at FROM presentation_embeddings WHERE presentation_id = $1
`

func (q *Queries) ListPresentationEmbeddings(ctx context.Context, presentationID string) ([]PresentationEmbedding, error) {
	rows, err := q.db.Query(ctx, listPresentationEmbeddings, presentationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresentationEmbedding{}
	for rows.Next() {
		var i PresentationEmbedding
		if err := rows.Scan(
			&i.ID,
			&i.PresentationID,
			&i.SourceType,
			&i.SourceID,
			&i.ChunkText,
			&i.EmbeddingReference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
