// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presentation_sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPresentationSession = `-- name: CreatePresentationSession :one
INSERT INTO presentation_sessions (id, presentation_id, business_id, name, enable_qna, auto_start)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, presentation_id, business_id, name, status, current_slide_number, enable_qna, auto_start, audience_count, question_count, started_at, ended_at, created_at, updated_at
`

type CreatePresentationSessionParams struct {
	ID             string `json:"id"`
	PresentationID string `json:"presentation_id"`
	BusinessID     string `json:"business_id"`
	Name           string `json:"name"`
	EnableQna      bool   `json:"enable_qna"`
	AutoStart      bool   `json:"auto_start"`
}

func (q *Queries) CreatePresentationSession(ctx context.Context, arg CreatePresentationSessionParams) (PresentationSession, error) {
	row := q.db.QueryRow(ctx, createPresentationSession,
		arg.ID,
		arg.PresentationID,
		arg.BusinessID,
		arg.Name,
		arg.EnableQna,
		arg.AutoStart,
	)
	var i PresentationSession
	err := row.Scan(
		&i.ID,
		&i.PresentationID,
		&i.BusinessID,
		&i.Name,
		&i.Status,
		&i.CurrentSlideNumber,
		&i.EnableQna,
		&i.AutoStart,
		&i.AudienceCount,
		&i.QuestionCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPresentationSession = `-- name: GetPresentationSession :one
SELECT id, presentation_id, business_id, name, status, current_slide_number, enable_qna, auto_start, audience_count, question_count, started_at, ended_at, created_at, updated_at FROM presentation_sessions WHERE id = $1 AND business_id = $2
`

type GetPresentationSessionParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) GetPresentationSession(ctx context.Context, arg GetPresentationSessionParams) (PresentationSession, error) {
	row := q.db.QueryRow(ctx, getPresentationSession, arg.ID, arg.BusinessID)
	var i PresentationSession
	err := row.Scan(
		&i.ID,
		&i.PresentationID,
		&i.BusinessID,
		&i.Name,
		&i.Status,
		&i.CurrentSlideNumber,
		&i.EnableQna,
		&i.AutoStart,
		&i.AudienceCount,
		&i.QuestionCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementSessionQuestionCount = `-- name: IncrementSessionQuestionCount :exec
UPDATE presentation_sessions SET question_count = question_count + 1, updated_at = NOW() WHERE id = $1 AND business_id = $2
`

type IncrementSessionQuestionCountParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) IncrementSessionQuestionCount(ctx context.Context, arg IncrementSessionQuestionCountParams) error {
	_, err := q.db.Exec(ctx, incrementSessionQuestionCount, arg.ID, arg.BusinessID)
	return err
}

const listPresentationSessionsForBusiness = `-- name: ListPresentationSessionsForBusiness :many
SELECT id, presentation_id, business_id, name, status, current_slide_number, enable_qna, auto_start, audience_count, question_count, started_at, ended_at, created_at, updated_at FROM presentation_sessions WHERE business_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPresentationSessionsForBusiness(ctx context.Context, businessID string) ([]PresentationSession, error) {
	rows, err := q.db.Query(ctx, listPresentationSessionsForBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresentationSession{}
	for rows.Next() {
		var i PresentationSession
		if err := rows.Scan(
			&i.ID,
			&i.PresentationID,
			&i.BusinessID,
			&i.Name,
			&i.Status,
			&i.CurrentSlideNumber,
			&i.EnableQna,
			&i.AutoStart,
			&i.AudienceCount,
			&i.QuestionCount,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionStatus = `-- name: SetSessionStatus :exec
UPDATE presentation_sessions SET status = $3, updated_at = NOW() WHERE id = $1 AND business_id = $2
`

type SetSessionStatusParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
	Status     string `json:"status"`
}

func (q *Queries) SetSessionStatus(ctx context.Context, arg SetSessionStatusParams) error {
	_, err := q.db.Exec(ctx, setSessionStatus, arg.ID, arg.BusinessID, arg.Status)
	return err
}

const updateSessionAudienceCount = `-- name: UpdateSessionAudienceCount :one
UPDATE presentation_sessions SET audience_count = $3, updated_at = NOW()
WHERE id = $1 AND business_id = $2
RETURNING id, presentation_id, business_id, name, status, current_slide_number, enable_qna, auto_start, audience_count, question_count, started_at, ended_at, created_at, updated_at
`

type UpdateSessionAudienceCountParams struct {
	ID            string `json:"id"`
	BusinessID    string `json:"business_id"`
	AudienceCount int32  `json:"audience_count"`
}

func (q *Queries) UpdateSessionAudienceCount(ctx context.Context, arg UpdateSessionAudienceCountParams) (PresentationSession, error) {
	row := q.db.QueryRow(ctx, updateSessionAudienceCount, arg.ID, arg.BusinessID, arg.AudienceCount)
	var i PresentationSession
	err := row.Scan(
		&i.ID,
		&i.PresentationID,
		&i.BusinessID,
		&i.Name,
		&i.Status,
		&i.CurrentSlideNumber,
		&i.EnableQna,
		&i.AutoStart,
		&i.AudienceCount,
		&i.QuestionCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionState = `-- name: UpdateSessionState :one
UPDATE presentation_sessions SET
  status = $3,
  current_slide_number = $4,
  started_at = COALESCE(started_at, $5),
  ended_at = COALESCE($6, ended_at),
  updated_at = NOW()
WHERE id = $1 AND business_id = $2
RETURNING id, presentation_id, business_id, name, status, current_slide_number, enable_qna, auto_start, audience_count, question_count, started_at, ended_at, created_at, updated_at
`

type UpdateSessionStateParams struct {
	ID                 string             `json:"id"`
	BusinessID         string             `json:"business_id"`
	Status             string             `json:"status"`
	CurrentSlideNumber int32              `json:"current_slide_number"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) (PresentationSession, error) {
	row := q.db.QueryRow(ctx, updateSessionState,
		arg.ID,
		arg.BusinessID,
		arg.Status,
		arg.CurrentSlideNumber,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i PresentationSession
	err := row.Scan(
		&i.ID,
		&i.PresentationID,
		&i.BusinessID,
		&i.Name,
		&i.Status,
		&i.CurrentSlideNumber,
		&i.EnableQna,
		&i.AutoStart,
		&i.AudienceCount,
		&i.QuestionCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
