// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presentation_slides.sql

package store

import (
	"context"
)

const createPresentationSlide = `-- name: CreatePresentationSlide :one
INSERT INTO presentation_slides (id, presentation_id, slide_number, title, content_json, notes, script, duration_seconds)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, presentation_id, slide_number, title, content_json, notes, script, image_url, duration_seconds, created_at
`

type CreatePresentationSlideParams struct {
	ID              string `json:"id"`
	PresentationID  string `json:"presentation_id"`
	SlideNumber     int32  `json:"slide_number"`
	Title           string `json:"title"`
	ContentJson     string `json:"content_json"`
	Notes           string `json:"notes"`
	Script          string `json:"script"`
	DurationSeconds int32  `json:"duration_seconds"`
}

func (q *Queries) CreatePresentationSlide(ctx context.Context, arg CreatePresentationSlideParams) (PresentationSlide, error) {
	row := q.db.QueryRow(ctx, createPresentationSlide,
		arg.ID,
		arg.PresentationID,
		arg.SlideNumber,
		arg.Title,
		arg.ContentJson,
		arg.Notes,
		arg.Script,
		arg.DurationSeconds,
	)
	var i PresentationSlide
	err := row.Scan(
		&i.ID,
		&i.PresentationID,
		&i.SlideNumber,
		&i.Title,
		&i.ContentJson,
		&i.Notes,
		&i.Script,
		&i.ImageUrl,
		&i.DurationSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const deletePresentationSlides = `-- name: DeletePresentationSlides :exec
DELETE FROM presentation_slides WHERE presentation_id = $1
`

func (q *Queries) DeletePresentationSlides(ctx context.Context, presentationID string) error {
	_, err := q.db.Exec(ctx, deletePresentationSlides, presentationID)
	return err
}

const listPresentationSlides = `-- name: ListPresentationSlides :many
SELECT id, presentation_id, slide_number, title, content_json, notes, script, image_url, duration_seconds, created_at FROM presentation_slides WHERE presentation_id = $1 ORDER BY slide_number
`

func (q *Queries) ListPresentationSlides(ctx context.Context, presentationID string) ([]PresentationSlide, error) {
	rows, err := q.db.Query(ctx, listPresentationSlides, presentationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresentationSlide{}
	for rows.Next() {
		var i PresentationSlide
		if err := rows.Scan(
			&i.ID,
			&i.PresentationID,
			&i.SlideNumber,
			&i.Title,
			&i.ContentJson,
			&i.Notes,
			&i.Script,
			&i.ImageUrl,
			&i.DurationSeconds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
