// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presentation_knowledge_entries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPresentationKnowledgeEntry = `-- name: CreatePresentationKnowledgeEntry :one
INSERT INTO presentation_knowledge_entries (id, presentation_id, title, content, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, presentation_id, title, content, sort_order, created_at, updated_at
`

type CreatePresentationKnowledgeEntryParams struct {
	ID             string `json:"id"`
	PresentationID string `json:"presentation_id"`
	Title          string `json:"title"`
	Content        string `json:"content"`
	SortOrder      int32  `json:"sort_order"`
}

func (q *Queries) CreatePresentationKnowledgeEntry(ctx context.Context, arg CreatePresentationKnowledgeEntryParams) (PresentationKnowledgeEntry, error) {
	row := q.db.QueryRow(ctx, createPresentationKnowledgeEntry,
		arg.ID,
		arg.PresentationID,
		arg.Title,
		arg.Content,
		arg.SortOrder,
	)
	var i PresentationKnowledgeEntry
	err := row.Scan(
		&i.ID,
		&i.PresentationID,
		&i.Title,
		&i.Content,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePresentationKnowledgeEntry = `-- name: DeletePresentationKnowledgeEntry :execrows
DELETE FROM presentation_knowledge_entries WHERE id = $1 AND presentation_id = $2
`

type DeletePresentationKnowledgeEntryParams struct {
	ID             string `json:"id"`
	PresentationID string `json:"presentation_id"`
}

func (q *Queries) DeletePresentationKnowledgeEntry(ctx context.Context, arg DeletePresentationKnowledgeEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePresentationKnowledgeEntry, arg.ID, arg.PresentationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPresentationKnowledgeEntry = `-- name: GetPresentationKnowledgeEntry :one
SELECT id, presentation_id, title, content, sort_order, created_at, updated_at FROM presentation_knowledge_entries WHERE id = $1 AND presentation_id = $2
`

type GetPresentationKnowledgeEntryParams struct {
	ID             string `json:"id"`
	PresentationID string `json:"presentation_id"`
}

func (q *Queries) GetPresentationKnowledgeEntry(ctx context.Context, arg GetPresentationKnowledgeEntryParams) (PresentationKnowledgeEntry, error) {
	row := q.db.QueryRow(ctx, getPresentationKnowledgeEntry, arg.ID, arg.PresentationID)
	var i PresentationKnowledgeEntry
	err := row.Scan(
		&i.ID,
		&i.PresentationID,
		&i.Title,
		&i.Content,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPresentationKnowledgeEntries = `-- name: ListPresentationKnowledgeEntries :many
SELECT id, presentation_id, title, content, sort_order, created_at, updated_at FROM presentation_knowledge_entries WHERE presentation_id = $1 ORDER BY sort_order, created_at
`

func (q *Queries) ListPresentationKnowledgeEntries(ctx context.Context, presentationID string) ([]PresentationKnowledgeEntry, error) {
	rows, err := q.db.Query(ctx, listPresentationKnowledgeEntries, presentationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresentationKnowledgeEntry{}
	for rows.Next() {
		var i PresentationKnowledgeEntry
		if err := rows.Scan(
			&i.ID,
			&i.PresentationID,
			&i.Title,
			&i.Content,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePresentationKnowledgeEntry = `-- name: UpdatePresentationKnowledgeEntry :one
UPDATE presentation_knowledge_entries SET
  title = COALESCE($1, title),
  content = COALESCE($2, content),
  sort_order = COALESCE($3, sort_order),
  updated_at = NOW()
WHERE id = $4 AND presentation_id = $5
RETURNING id, presentation_id, title, content, sort_order, created_at, updated_at
`

type UpdatePresentationKnowledgeEntryParams struct {
	Title          pgtype.Text `json:"title"`
	Content        pgtype.Text `json:"content"`
	SortOrder      pgtype.Int4 `json:"sort_order"`
	ID             string      `json:"id"`
	PresentationID string      `json:"presentation_id"`
}

func (q *Queries) UpdatePresentationKnowledgeEntry(ctx context.Context, arg UpdatePresentationKnowledgeEntryParams) (PresentationKnowledgeEntry, error) {
	row := q.db.QueryRow(ctx, updatePresentationKnowledgeEntry,
		arg.Title,
		arg.Content,
		arg.SortOrder,
		arg.ID,
		arg.PresentationID,
	)
	var i PresentationKnowledgeEntry
	err := row.Scan(
		&i.ID,
		&i.PresentationID,
		&i.Title,
		&i.Content,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
