// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presentation_presentations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completePresentation = `-- name: CompletePresentation :exec
UPDATE presentations SET status = 'completed', updated_at = NOW() WHERE id = $1 AND business_id = $2
`

type CompletePresentationParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) CompletePresentation(ctx context.Context, arg CompletePresentationParams) error {
	_, err := q.db.Exec(ctx, completePresentation, arg.ID, arg.BusinessID)
	return err
}

const completePresentationProcessing = `-- name: CompletePresentationProcessing :exec
UPDATE presentations SET
  status = 'ready',
  processing_step = 'completed',
  processing_error = '',
  greeting_script = $3,
  closing_script = $4,
  estimated_duration = $5,
  total_slides = $6,
  updated_at = NOW()
WHERE id = $1 AND business_id = $2
`

type CompletePresentationProcessingParams struct {
	ID                string `json:"id"`
	BusinessID        string `json:"business_id"`
	GreetingScript    string `json:"greeting_script"`
	ClosingScript     string `json:"closing_script"`
	EstimatedDuration int32  `json:"estimated_duration"`
	TotalSlides       int32  `json:"total_slides"`
}

func (q *Queries) CompletePresentationProcessing(ctx context.Context, arg CompletePresentationProcessingParams) error {
	_, err := q.db.Exec(ctx, completePresentationProcessing,
		arg.ID,
		arg.BusinessID,
		arg.GreetingScript,
		arg.ClosingScript,
		arg.EstimatedDuration,
		arg.TotalSlides,
	)
	return err
}

const createPresentation = `-- name: CreatePresentation :one
INSERT INTO presentations (id, business_id, created_by, title, description, language, category)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, business_id, created_by, title, description, language, category, status, processing_step, processing_error, total_slides, estimated_duration, greeting_script, closing_script, thumbnail_url, deleted_at, created_at, updated_at
`

type CreatePresentationParams struct {
	ID          string      `json:"id"`
	BusinessID  string      `json:"business_id"`
	CreatedBy   pgtype.Text `json:"created_by"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Language    string      `json:"language"`
	Category    string      `json:"category"`
}

func (q *Queries) CreatePresentation(ctx context.Context, arg CreatePresentationParams) (Presentation, error) {
	row := q.db.QueryRow(ctx, createPresentation,
		arg.ID,
		arg.BusinessID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.Language,
		arg.Category,
	)
	var i Presentation
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.Category,
		&i.Status,
		&i.ProcessingStep,
		&i.ProcessingError,
		&i.TotalSlides,
		&i.EstimatedDuration,
		&i.GreetingScript,
		&i.ClosingScript,
		&i.ThumbnailUrl,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPresentation = `-- name: GetPresentation :one
SELECT id, business_id, created_by, title, description, language, category, status, processing_step, processing_error, total_slides, estimated_duration, greeting_script, closing_script, thumbnail_url, deleted_at, created_at, updated_at FROM presentations WHERE id = $1 AND business_id = $2 AND deleted_at IS NULL
`

type GetPresentationParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) GetPresentation(ctx context.Context, arg GetPresentationParams) (Presentation, error) {
	row := q.db.QueryRow(ctx, getPresentation, arg.ID, arg.BusinessID)
	var i Presentation
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.Category,
		&i.Status,
		&i.ProcessingStep,
		&i.ProcessingError,
		&i.TotalSlides,
		&i.EstimatedDuration,
		&i.GreetingScript,
		&i.ClosingScript,
		&i.ThumbnailUrl,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPresentationsForBusiness = `-- name: ListPresentationsForBusiness :many
SELECT id, business_id, created_by, title, description, language, category, status, processing_step, processing_error, total_slides, estimated_duration, greeting_script, closing_script, thumbnail_url, deleted_at, created_at, updated_at FROM presentations WHERE business_id = $1 AND deleted_at IS NULL ORDER BY updated_at DESC
`

func (q *Queries) ListPresentationsForBusiness(ctx context.Context, businessID string) ([]Presentation, error) {
	rows, err := q.db.Query(ctx, listPresentationsForBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Presentation{}
	for rows.Next() {
		var i Presentation
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.Language,
			&i.Category,
			&i.Status,
			&i.ProcessingStep,
			&i.ProcessingError,
			&i.TotalSlides,
			&i.EstimatedDuration,
			&i.GreetingScript,
			&i.ClosingScript,
			&i.ThumbnailUrl,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetPresentationToDraft = `-- name: ResetPresentationToDraft :exec
UPDATE presentations SET status = 'draft', updated_at = NOW() WHERE id = $1 AND business_id = $2
`

type ResetPresentationToDraftParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) ResetPresentationToDraft(ctx context.Context, arg ResetPresentationToDraftParams) error {
	_, err := q.db.Exec(ctx, resetPresentationToDraft, arg.ID, arg.BusinessID)
	return err
}

const setPresentationLive = `-- name: SetPresentationLive :exec
UPDATE presentations SET status = 'live', updated_at = NOW() WHERE id = $1 AND business_id = $2
`

type SetPresentationLiveParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) SetPresentationLive(ctx context.Context, arg SetPresentationLiveParams) error {
	_, err := q.db.Exec(ctx, setPresentationLive, arg.ID, arg.BusinessID)
	return err
}

const setPresentationStatus = `-- name: SetPresentationStatus :exec
UPDATE presentations SET status = $3, processing_step = $4, processing_error = $5, updated_at = NOW()
WHERE id = $1 AND business_id = $2
`

type SetPresentationStatusParams struct {
	ID              string `json:"id"`
	BusinessID      string `json:"business_id"`
	Status          string `json:"status"`
	ProcessingStep  string `json:"processing_step"`
	ProcessingError string `json:"processing_error"`
}

func (q *Queries) SetPresentationStatus(ctx context.Context, arg SetPresentationStatusParams) error {
	_, err := q.db.Exec(ctx, setPresentationStatus,
		arg.ID,
		arg.BusinessID,
		arg.Status,
		arg.ProcessingStep,
		arg.ProcessingError,
	)
	return err
}

const softDeletePresentation = `-- name: SoftDeletePresentation :execrows
UPDATE presentations SET deleted_at = NOW(), status = 'archived', updated_at = NOW()
WHERE id = $1 AND business_id = $2 AND deleted_at IS NULL
`

type SoftDeletePresentationParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) SoftDeletePresentation(ctx context.Context, arg SoftDeletePresentationParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePresentation, arg.ID, arg.BusinessID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePresentationDetails = `-- name: UpdatePresentationDetails :one
UPDATE presentations SET
  title = COALESCE($1, title),
  description = COALESCE($2, description),
  language = COALESCE($3, language),
  category = COALESCE($4, category),
  updated_at = NOW()
WHERE id = $5 AND business_id = $6 AND deleted_at IS NULL
RETURNING id, business_id, created_by, title, description, language, category, status, processing_step, processing_error, total_slides, estimated_duration, greeting_script, closing_script, thumbnail_url, deleted_at, created_at, updated_at
`

type UpdatePresentationDetailsParams struct {
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	Language    pgtype.Text `json:"language"`
	Category    pgtype.Text `json:"category"`
	ID          string      `json:"id"`
	BusinessID  string      `json:"business_id"`
}

func (q *Queries) UpdatePresentationDetails(ctx context.Context, arg UpdatePresentationDetailsParams) (Presentation, error) {
	row := q.db.QueryRow(ctx, updatePresentationDetails,
		arg.Title,
		arg.Description,
		arg.Language,
		arg.Category,
		arg.ID,
		arg.BusinessID,
	)
	var i Presentation
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.Category,
		&i.Status,
		&i.ProcessingStep,
		&i.ProcessingError,
		&i.TotalSlides,
		&i.EstimatedDuration,
		&i.GreetingScript,
		&i.ClosingScript,
		&i.ThumbnailUrl,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
