// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presentation_questions.sql

package store

import (
	"context"
)

const answerPresentationQuestion = `-- name: AnswerPresentationQuestion :one
UPDATE presentation_questions SET
  answer = $2,
  status = 'answered',
  source_references = $3,
  answered_at = NOW()
WHERE id = $1
RETURNING id, session_id, question, answer, status, moderation_result, source_references, created_at, answered_at
`

type AnswerPresentationQuestionParams struct {
	ID               string `json:"id"`
	Answer           string `json:"answer"`
	SourceReferences string `json:"source_references"`
}

func (q *Queries) AnswerPresentationQuestion(ctx context.Context, arg AnswerPresentationQuestionParams) (PresentationQuestion, error) {
	row := q.db.QueryRow(ctx, answerPresentationQuestion, arg.ID, arg.Answer, arg.SourceReferences)
	var i PresentationQuestion
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Question,
		&i.Answer,
		&i.Status,
		&i.ModerationResult,
		&i.SourceReferences,
		&i.CreatedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const createPresentationQuestion = `-- name: CreatePresentationQuestion :one
INSERT INTO presentation_questions (id, session_id, question, status, moderation_result)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, question, answer, status, moderation_result, source_references, created_at, answered_at
`

type CreatePresentationQuestionParams struct {
	ID               string `json:"id"`
	SessionID        string `json:"session_id"`
	Question         string `json:"question"`
	Status           string `json:"status"`
	ModerationResult string `json:"moderation_result"`
}

func (q *Queries) CreatePresentationQuestion(ctx context.Context, arg CreatePresentationQuestionParams) (PresentationQuestion, error) {
	row := q.db.QueryRow(ctx, createPresentationQuestion,
		arg.ID,
		arg.SessionID,
		arg.Question,
		arg.Status,
		arg.ModerationResult,
	)
	var i PresentationQuestion
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Question,
		&i.Answer,
		&i.Status,
		&i.ModerationResult,
		&i.SourceReferences,
		&i.CreatedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const listPresentationQuestions = `-- name: ListPresentationQuestions :many
SELECT id, session_id, question, answer, status, moderation_result, source_references, created_at, answered_at FROM presentation_questions WHERE session_id = $1 ORDER BY created_at
`

func (q *Queries) ListPresentationQuestions(ctx context.Context, sessionID string) ([]PresentationQuestion, error) {
	rows, err := q.db.Query(ctx, listPresentationQuestions, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresentationQuestion{}
	for rows.Next() {
		var i PresentationQuestion
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Question,
			&i.Answer,
			&i.Status,
			&i.ModerationResult,
			&i.SourceReferences,
			&i.CreatedAt,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
