// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presentation_files.sql

package store

import (
	"context"
)

const createPresentationFile = `-- name: CreatePresentationFile :one
INSERT INTO presentation_files (id, presentation_id, file_name, file_type, size_bytes, storage_path)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, presentation_id, file_name, file_type, size_bytes, storage_path, status, created_at
`

type CreatePresentationFileParams struct {
	ID             string `json:"id"`
	PresentationID string `json:"presentation_id"`
	FileName       string `json:"file_name"`
	FileType       string `json:"file_type"`
	SizeBytes      int32  `json:"size_bytes"`
	StoragePath    string `json:"storage_path"`
}

func (q *Queries) CreatePresentationFile(ctx context.Context, arg CreatePresentationFileParams) (PresentationFile, error) {
	row := q.db.QueryRow(ctx, createPresentationFile,
		arg.ID,
		arg.PresentationID,
		arg.FileName,
		arg.FileType,
		arg.SizeBytes,
		arg.StoragePath,
	)
	var i PresentationFile
	err := row.Scan(
		&i.ID,
		&i.PresentationID,
		&i.FileName,
		&i.FileType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPresentationFile = `-- name: GetPresentationFile :one
SELECT id, presentation_id, file_name, file_type, size_bytes, storage_path, status, created_at FROM presentation_files WHERE id = $1 AND presentation_id = $2
`

type GetPresentationFileParams struct {
	ID             string `json:"id"`
	PresentationID string `json:"presentation_id"`
}

func (q *Queries) GetPresentationFile(ctx context.Context, arg GetPresentationFileParams) (PresentationFile, error) {
	row := q.db.QueryRow(ctx, getPresentationFile, arg.ID, arg.PresentationID)
	var i PresentationFile
	err := row.Scan(
		&i.ID,
		&i.PresentationID,
		&i.FileName,
		&i.FileType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPresentationFileByType = `-- name: GetPresentationFileByType :one
SELECT id, presentation_id, file_name, file_type, size_bytes, storage_path, status, created_at FROM presentation_files WHERE presentation_id = $1 AND file_type = $2 ORDER BY created_at DESC LIMIT 1
`

type GetPresentationFileByTypeParams struct {
	PresentationID string `json:"presentation_id"`
	FileType       string `json:"file_type"`
}

func (q *Queries) GetPresentationFileByType(ctx context.Context, arg GetPresentationFileByTypeParams) (PresentationFile, error) {
	row := q.db.QueryRow(ctx, getPresentationFileByType, arg.PresentationID, arg.FileType)
	var i PresentationFile
	err := row.Scan(
		&i.ID,
		&i.PresentationID,
		&i.FileName,
		&i.FileType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPresentationFiles = `-- name: ListPresentationFiles :many
SELECT id, presentation_id, file_name, file_type, size_bytes, storage_path, status, created_at FROM presentation_files WHERE presentation_id = $1 ORDER BY created_at
`

func (q *Queries) ListPresentationFiles(ctx context.Context, presentationID string) ([]PresentationFile, error) {
	rows, err := q.db.Query(ctx, listPresentationFiles, presentationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PresentationFile{}
	for rows.Next() {
		var i PresentationFile
		if err := rows.Scan(
			&i.ID,
			&i.PresentationID,
			&i.FileName,
			&i.FileType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
