// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  id, business_id, product_id, name, price, discount_percent,
  category, description, image_url, is_active, sort_order, duration_min
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, business_id, product_id, name, price, discount_percent, category, description, image_url, is_active, sort_order, duration_min
`

type CreateProductParams struct {
	ID              string  `json:"id"`
	BusinessID      string  `json:"business_id"`
	ProductID       string  `json:"product_id"`
	Name            string  `json:"name"`
	Price           float64 `json:"price"`
	DiscountPercent float64 `json:"discount_percent"`
	Category        string  `json:"category"`
	Description     string  `json:"description"`
	ImageUrl        string  `json:"image_url"`
	IsActive        bool    `json:"is_active"`
	SortOrder       int32   `json:"sort_order"`
	DurationMin     int32   `json:"duration_min"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.BusinessID,
		arg.ProductID,
		arg.Name,
		arg.Price,
		arg.DiscountPercent,
		arg.Category,
		arg.Description,
		arg.ImageUrl,
		arg.IsActive,
		arg.SortOrder,
		arg.DurationMin,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ProductID,
		&i.Name,
		&i.Price,
		&i.DiscountPercent,
		&i.Category,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.SortOrder,
		&i.DurationMin,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :execrows
DELETE FROM products WHERE id = $1 AND business_id = $2
`

type DeleteProductParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProduct, arg.ID, arg.BusinessID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveProductBySlug = `-- name: GetActiveProductBySlug :one
SELECT id, business_id, product_id, name, price, discount_percent, category, description, image_url, is_active, sort_order, duration_min FROM products WHERE business_id = $1 AND product_id = $2 AND is_active = TRUE
`

type GetActiveProductBySlugParams struct {
	BusinessID string `json:"business_id"`
	ProductID  string `json:"product_id"`
}

// Looks up a product by its business-scoped human slug (product_id, not
// the row's own id) — used by the booking module to validate a
// treatment exists and is bookable, and will be used by the future
// voice-ordering flow the same way.
func (q *Queries) GetActiveProductBySlug(ctx context.Context, arg GetActiveProductBySlugParams) (Product, error) {
	row := q.db.QueryRow(ctx, getActiveProductBySlug, arg.BusinessID, arg.ProductID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ProductID,
		&i.Name,
		&i.Price,
		&i.DiscountPercent,
		&i.Category,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.SortOrder,
		&i.DurationMin,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, business_id, product_id, name, price, discount_percent, category, description, image_url, is_active, sort_order, duration_min FROM products WHERE id = $1 AND business_id = $2
`

type GetProductParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, arg.ID, arg.BusinessID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ProductID,
		&i.Name,
		&i.Price,
		&i.DiscountPercent,
		&i.Category,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.SortOrder,
		&i.DurationMin,
	)
	return i, err
}

const listActiveProductsForBusiness = `-- name: ListActiveProductsForBusiness :many
SELECT id, business_id, product_id, name, price, discount_percent, category, description, image_url, is_active, sort_order, duration_min FROM products WHERE business_id = $1 AND is_active = TRUE ORDER BY sort_order, name
`

// Active only — used by the streaming module's voice tools
// (search_products, list_treatments) which should never surface a
// disabled item to a live conversation.
func (q *Queries) ListActiveProductsForBusiness(ctx context.Context, businessID string) ([]Product, error) {
	rows, err := q.db.Query(ctx, listActiveProductsForBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ProductID,
			&i.Name,
			&i.Price,
			&i.DiscountPercent,
			&i.Category,
			&i.Description,
			&i.ImageUrl,
			&i.IsActive,
			&i.SortOrder,
			&i.DurationMin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsForBusiness = `-- name: ListProductsForBusiness :many
SELECT id, business_id, product_id, name, price, discount_percent, category, description, image_url, is_active, sort_order, duration_min FROM products WHERE business_id = $1 ORDER BY sort_order, name
`

func (q *Queries) ListProductsForBusiness(ctx context.Context, businessID string) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsForBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ProductID,
			&i.Name,
			&i.Price,
			&i.DiscountPercent,
			&i.Category,
			&i.Description,
			&i.ImageUrl,
			&i.IsActive,
			&i.SortOrder,
			&i.DurationMin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
  product_id = COALESCE($1, product_id),
  name = COALESCE($2, name),
  price = COALESCE($3, price),
  discount_percent = COALESCE($4, discount_percent),
  category = COALESCE($5, category),
  description = COALESCE($6, description),
  image_url = COALESCE($7, image_url),
  is_active = COALESCE($8, is_active),
  sort_order = COALESCE($9, sort_order),
  duration_min = COALESCE($10, duration_min)
WHERE id = $11 AND business_id = $12
RETURNING id, business_id, product_id, name, price, discount_percent, category, description, image_url, is_active, sort_order, duration_min
`

type UpdateProductParams struct {
	ProductID       pgtype.Text   `json:"product_id"`
	Name            pgtype.Text   `json:"name"`
	Price           pgtype.Float8 `json:"price"`
	DiscountPercent pgtype.Float8 `json:"discount_percent"`
	Category        pgtype.Text   `json:"category"`
	Description     pgtype.Text   `json:"description"`
	ImageUrl        pgtype.Text   `json:"image_url"`
	IsActive        pgtype.Bool   `json:"is_active"`
	SortOrder       pgtype.Int4   `json:"sort_order"`
	DurationMin     pgtype.Int4   `json:"duration_min"`
	ID              string        `json:"id"`
	BusinessID      string        `json:"business_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ProductID,
		arg.Name,
		arg.Price,
		arg.DiscountPercent,
		arg.Category,
		arg.Description,
		arg.ImageUrl,
		arg.IsActive,
		arg.SortOrder,
		arg.DurationMin,
		arg.ID,
		arg.BusinessID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ProductID,
		&i.Name,
		&i.Price,
		&i.DiscountPercent,
		&i.Category,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.SortOrder,
		&i.DurationMin,
	)
	return i, err
}
