// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AnswerPresentationQuestion(ctx context.Context, arg AnswerPresentationQuestionParams) (PresentationQuestion, error)
	// Returns -1 (a sentinel; duration can never be negative) when there
	// are no matching rows, since sqlc can't infer AVG()'s nullability here
	// and pgx errors scanning SQL NULL into a non-pointer float64.
	AvgSessionDurationSeconds(ctx context.Context, businessID string) (float64, error)
	CancelAppointment(ctx context.Context, arg CancelAppointmentParams) (Appointment, error)
	CheckBusinessMembership(ctx context.Context, arg CheckBusinessMembershipParams) (string, error)
	CompletePhotoSession(ctx context.Context, arg CompletePhotoSessionParams) (PhotoSession, error)
	CompletePresentation(ctx context.Context, arg CompletePresentationParams) error
	CompletePresentationProcessing(ctx context.Context, arg CompletePresentationProcessingParams) error
	CountActiveBusinesses(ctx context.Context) (int64, error)
	CountActiveSessions(ctx context.Context, businessID string) (int64, error)
	CountAuditLogs(ctx context.Context) (int64, error)
	CountAuditLogsForTarget(ctx context.Context, arg CountAuditLogsForTargetParams) (int64, error)
	CountBusinessesForPlatform(ctx context.Context, search pgtype.Text) (int64, error)
	CountConfirmedOrdersSince(ctx context.Context, arg CountConfirmedOrdersSinceParams) (CountConfirmedOrdersSinceRow, error)
	CountPlatformAdmins(ctx context.Context) (int64, error)
	CountSessionsSince(ctx context.Context, arg CountSessionsSinceParams) (int64, error)
	CountTranscriptMessagesForSessions(ctx context.Context, sessionIds []string) ([]CountTranscriptMessagesForSessionsRow, error)
	CountUsageEventsSince(ctx context.Context, arg CountUsageEventsSinceParams) (int64, error)
	CountUsersByStatus(ctx context.Context, status string) (int64, error)
	CountUsersForPlatform(ctx context.Context, search pgtype.Text) (int64, error)
	CreateAIRules(ctx context.Context, arg CreateAIRulesParams) (AiRule, error)
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error)
	CreateBusinessHour(ctx context.Context, arg CreateBusinessHourParams) (BusinessHour, error)
	CreateBusinessMember(ctx context.Context, arg CreateBusinessMemberParams) (BusinessMember, error)
	CreateKnowledgeEntry(ctx context.Context, arg CreateKnowledgeEntryParams) (KnowledgeEntry, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePhotoSession(ctx context.Context, arg CreatePhotoSessionParams) (PhotoSession, error)
	CreatePhotoSettings(ctx context.Context, businessID string) (PhotoSetting, error)
	CreatePlatformAdmin(ctx context.Context, arg CreatePlatformAdminParams) (PlatformAdmin, error)
	CreatePresentation(ctx context.Context, arg CreatePresentationParams) (Presentation, error)
	CreatePresentationEmbedding(ctx context.Context, arg CreatePresentationEmbeddingParams) (PresentationEmbedding, error)
	CreatePresentationFile(ctx context.Context, arg CreatePresentationFileParams) (PresentationFile, error)
	CreatePresentationKnowledgeEntry(ctx context.Context, arg CreatePresentationKnowledgeEntryParams) (PresentationKnowledgeEntry, error)
	CreatePresentationQuestion(ctx context.Context, arg CreatePresentationQuestionParams) (PresentationQuestion, error)
	CreatePresentationSession(ctx context.Context, arg CreatePresentationSessionParams) (PresentationSession, error)
	CreatePresentationSlide(ctx context.Context, arg CreatePresentationSlideParams) (PresentationSlide, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateTranscriptMessage(ctx context.Context, arg CreateTranscriptMessageParams) (TranscriptMessage, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVoiceSession(ctx context.Context, arg CreateVoiceSessionParams) (VoiceSession, error)
	DailyConfirmedOrderStats(ctx context.Context, arg DailyConfirmedOrderStatsParams) ([]DailyConfirmedOrderStatsRow, error)
	DeleteAllKnowledgeEntries(ctx context.Context, businessID string) (int64, error)
	DeleteBusinessAiRules(ctx context.Context, businessID string) error
	DeleteBusinessAppointments(ctx context.Context, businessID string) error
	DeleteBusinessHours(ctx context.Context, businessID string) error
	// DeleteBusinessHours already exists in business_hours.sql — reused as-is.
	DeleteBusinessKnowledgeEntries(ctx context.Context, businessID string) error
	DeleteBusinessMembersRows(ctx context.Context, businessID string) error
	DeleteBusinessOrders(ctx context.Context, businessID string) error
	DeleteBusinessProducts(ctx context.Context, businessID string) error
	DeleteBusinessRow(ctx context.Context, id string) error
	DeleteBusinessTranscriptMessages(ctx context.Context, businessID string) error
	DeleteBusinessUsageEvents(ctx context.Context, businessID string) error
	DeleteBusinessVoiceSessions(ctx context.Context, businessID string) error
	DeleteKnowledgeEmbeddings(ctx context.Context, arg DeleteKnowledgeEmbeddingsParams) error
	DeleteKnowledgeEntry(ctx context.Context, arg DeleteKnowledgeEntryParams) (int64, error)
	DeleteNonKnowledgeEmbeddings(ctx context.Context, presentationID string) error
	DeletePhotoSession(ctx context.Context, arg DeletePhotoSessionParams) (PhotoSession, error)
	DeletePhotoSessionByID(ctx context.Context, id string) error
	DeletePresentationKnowledgeEntry(ctx context.Context, arg DeletePresentationKnowledgeEntryParams) (int64, error)
	DeletePresentationSlides(ctx context.Context, presentationID string) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) (int64, error)
	EndVoiceSession(ctx context.Context, arg EndVoiceSessionParams) error
	ExpireQrTokens(ctx context.Context) (int64, error)
	GetAIRules(ctx context.Context, businessID string) (AiRule, error)
	// Looks up a product by its business-scoped human slug (product_id, not
	// the row's own id) — used by the booking module to validate a
	// treatment exists and is bookable, and will be used by the future
	// voice-ordering flow the same way.
	GetActiveProductBySlug(ctx context.Context, arg GetActiveProductBySlugParams) (Product, error)
	GetAppointment(ctx context.Context, arg GetAppointmentParams) (Appointment, error)
	GetBusinessByID(ctx context.Context, id string) (Business, error)
	GetBusinessBySlug(ctx context.Context, slug string) (Business, error)
	GetBusinessMemberCount(ctx context.Context, businessID string) (int64, error)
	GetBusinessOwnerUserID(ctx context.Context, businessID string) (string, error)
	GetBusinessPresentationCount(ctx context.Context, businessID string) (int64, error)
	GetBusinessProductCount(ctx context.Context, businessID string) (int64, error)
	GetMostRecentOrderForVoiceSession(ctx context.Context, voiceSessionID pgtype.Text) (Order, error)
	GetPhotoBrandingPathsForBusiness(ctx context.Context, businessID string) (GetPhotoBrandingPathsForBusinessRow, error)
	GetPhotoSession(ctx context.Context, arg GetPhotoSessionParams) (PhotoSession, error)
	GetPhotoSessionByToken(ctx context.Context, qrToken pgtype.Text) (PhotoSession, error)
	GetPhotoSettings(ctx context.Context, businessID string) (PhotoSetting, error)
	GetPlatformAdminByEmail(ctx context.Context, email string) (PlatformAdmin, error)
	GetPlatformAdminByID(ctx context.Context, id string) (PlatformAdmin, error)
	GetPresentation(ctx context.Context, arg GetPresentationParams) (Presentation, error)
	GetPresentationFile(ctx context.Context, arg GetPresentationFileParams) (PresentationFile, error)
	GetPresentationFileByType(ctx context.Context, arg GetPresentationFileByTypeParams) (PresentationFile, error)
	GetPresentationKnowledgeEntry(ctx context.Context, arg GetPresentationKnowledgeEntryParams) (PresentationKnowledgeEntry, error)
	GetPresentationSession(ctx context.Context, arg GetPresentationSessionParams) (PresentationSession, error)
	GetProduct(ctx context.Context, arg GetProductParams) (Product, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetVoiceSession(ctx context.Context, arg GetVoiceSessionParams) (VoiceSession, error)
	HasAIRulesConfigured(ctx context.Context, businessID string) (bool, error)
	IncrementSessionQuestionCount(ctx context.Context, arg IncrementSessionQuestionCountParams) error
	ListActiveAppointmentsInRange(ctx context.Context, arg ListActiveAppointmentsInRangeParams) ([]Appointment, error)
	// Active only — used by the streaming module's voice tools
	// (search_products, list_treatments) which should never surface a
	// disabled item to a live conversation.
	ListActiveProductsForBusiness(ctx context.Context, businessID string) ([]Product, error)
	ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]Appointment, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListAuditLogsForTarget(ctx context.Context, arg ListAuditLogsForTargetParams) ([]ListAuditLogsForTargetRow, error)
	ListBusinessHours(ctx context.Context, businessID string) ([]BusinessHour, error)
	ListBusinessMembersForPlatform(ctx context.Context, businessID string) ([]ListBusinessMembersForPlatformRow, error)
	ListBusinessMembershipsForUser(ctx context.Context, userID string) ([]ListBusinessMembershipsForUserRow, error)
	ListBusinessesForPlatform(ctx context.Context, arg ListBusinessesForPlatformParams) ([]Business, error)
	ListBusinessesForUser(ctx context.Context, userID string) ([]ListBusinessesForUserRow, error)
	ListExpiredPhotoSessionsForBusiness(ctx context.Context, arg ListExpiredPhotoSessionsForBusinessParams) ([]PhotoSession, error)
	ListKnowledgeEntries(ctx context.Context, businessID string) ([]KnowledgeEntry, error)
	ListOrderItemsForOrders(ctx context.Context, orderIds []string) ([]OrderItem, error)
	ListOrdersForBusiness(ctx context.Context, businessID string) ([]Order, error)
	ListOrdersForVoiceSessions(ctx context.Context, sessionIds []string) ([]Order, error)
	ListPhotoGalleryForBusiness(ctx context.Context, arg ListPhotoGalleryForBusinessParams) ([]PhotoSession, error)
	ListPhotoSettingsForCleanup(ctx context.Context) ([]PhotoSetting, error)
	ListPhotoStoragePathsForBusiness(ctx context.Context, businessID string) ([]ListPhotoStoragePathsForBusinessRow, error)
	ListPresentationEmbeddings(ctx context.Context, presentationID string) ([]PresentationEmbedding, error)
	ListPresentationFiles(ctx context.Context, presentationID string) ([]PresentationFile, error)
	ListPresentationKnowledgeEntries(ctx context.Context, presentationID string) ([]PresentationKnowledgeEntry, error)
	ListPresentationQuestions(ctx context.Context, sessionID string) ([]PresentationQuestion, error)
	ListPresentationSessionsForBusiness(ctx context.Context, businessID string) ([]PresentationSession, error)
	ListPresentationSlides(ctx context.Context, presentationID string) ([]PresentationSlide, error)
	// Cross-table operational queries backing internal/tenantlifecycle.DeleteBusiness.
	// Not owned by any single domain module — sqlc doesn't care which .sql
	// file a query is defined in, all land in the shared store package.
	ListPresentationStoragePathsForBusiness(ctx context.Context, businessID string) ([]string, error)
	ListPresentationsForBusiness(ctx context.Context, businessID string) ([]Presentation, error)
	ListProductsForBusiness(ctx context.Context, businessID string) ([]Product, error)
	ListRecentUserSignups(ctx context.Context, limit int32) ([]User, error)
	ListTranscriptMessagesForSession(ctx context.Context, voiceSessionID string) ([]TranscriptMessage, error)
	ListTranscriptMessagesForSessions(ctx context.Context, sessionIds []string) ([]TranscriptMessage, error)
	ListUsersForPlatform(ctx context.Context, arg ListUsersForPlatformParams) ([]User, error)
	ListVoiceSessionsForBusiness(ctx context.Context, businessID string) ([]VoiceSession, error)
	MarkPhotoSessionDownloaded(ctx context.Context, id string) (PhotoSession, error)
	RecordUsageEvent(ctx context.Context, arg RecordUsageEventParams) (UsageEvent, error)
	ResetPresentationToDraft(ctx context.Context, arg ResetPresentationToDraftParams) error
	SetAIRulesAvatarURL(ctx context.Context, arg SetAIRulesAvatarURLParams) (AiRule, error)
	SetPhotoFrameURL(ctx context.Context, arg SetPhotoFrameURLParams) (PhotoSetting, error)
	SetPhotoLogoURL(ctx context.Context, arg SetPhotoLogoURLParams) (PhotoSetting, error)
	SetPhotoSessionResponse(ctx context.Context, arg SetPhotoSessionResponseParams) (PhotoSession, error)
	SetPhotoSessionUpload(ctx context.Context, arg SetPhotoSessionUploadParams) (PhotoSession, error)
	SetPlatformAdminTOTP(ctx context.Context, arg SetPlatformAdminTOTPParams) (PlatformAdmin, error)
	SetPresentationLive(ctx context.Context, arg SetPresentationLiveParams) error
	SetPresentationStatus(ctx context.Context, arg SetPresentationStatusParams) error
	SetSessionStatus(ctx context.Context, arg SetSessionStatusParams) error
	SoftDeletePresentation(ctx context.Context, arg SoftDeletePresentationParams) (int64, error)
	TopProductsForBusiness(ctx context.Context, businessID string) ([]TopProductsForBusinessRow, error)
	UpdateAIRules(ctx context.Context, arg UpdateAIRulesParams) (AiRule, error)
	UpdateBusinessAppearance(ctx context.Context, arg UpdateBusinessAppearanceParams) (Business, error)
	UpdateBusinessBackgroundURL(ctx context.Context, arg UpdateBusinessBackgroundURLParams) (Business, error)
	UpdateBusinessGeneral(ctx context.Context, arg UpdateBusinessGeneralParams) (Business, error)
	UpdateBusinessOnboarding(ctx context.Context, arg UpdateBusinessOnboardingParams) (Business, error)
	UpdateBusinessPaymentQRURL(ctx context.Context, arg UpdateBusinessPaymentQRURLParams) (Business, error)
	UpdateBusinessStatus(ctx context.Context, arg UpdateBusinessStatusParams) (Business, error)
	UpdateKnowledgeEntry(ctx context.Context, arg UpdateKnowledgeEntryParams) (KnowledgeEntry, error)
	UpdateOrderCustomerName(ctx context.Context, arg UpdateOrderCustomerNameParams) (Order, error)
	UpdatePhotoSettings(ctx context.Context, arg UpdatePhotoSettingsParams) (PhotoSetting, error)
	UpdatePlatformAdminLastLogin(ctx context.Context, id string) error
	UpdatePlatformAdminPasswordHash(ctx context.Context, arg UpdatePlatformAdminPasswordHashParams) error
	UpdatePresentationDetails(ctx context.Context, arg UpdatePresentationDetailsParams) (Presentation, error)
	UpdatePresentationKnowledgeEntry(ctx context.Context, arg UpdatePresentationKnowledgeEntryParams) (PresentationKnowledgeEntry, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateSessionAudienceCount(ctx context.Context, arg UpdateSessionAudienceCountParams) (PresentationSession, error)
	UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) (PresentationSession, error)
	UpdateUserCountry(ctx context.Context, arg UpdateUserCountryParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id string) error
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
}

var _ Querier = (*Queries)(nil)
