// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_lifecycle.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBusinessAiRules = `-- name: DeleteBusinessAiRules :exec
DELETE FROM ai_rules WHERE business_id = $1
`

func (q *Queries) DeleteBusinessAiRules(ctx context.Context, businessID string) error {
	_, err := q.db.Exec(ctx, deleteBusinessAiRules, businessID)
	return err
}

const deleteBusinessAppointments = `-- name: DeleteBusinessAppointments :exec
DELETE FROM appointments WHERE business_id = $1
`

func (q *Queries) DeleteBusinessAppointments(ctx context.Context, businessID string) error {
	_, err := q.db.Exec(ctx, deleteBusinessAppointments, businessID)
	return err
}

const deleteBusinessKnowledgeEntries = `-- name: DeleteBusinessKnowledgeEntries :exec

DELETE FROM knowledge_entries WHERE business_id = $1
`

// DeleteBusinessHours already exists in business_hours.sql — reused as-is.
func (q *Queries) DeleteBusinessKnowledgeEntries(ctx context.Context, businessID string) error {
	_, err := q.db.Exec(ctx, deleteBusinessKnowledgeEntries, businessID)
	return err
}

const deleteBusinessMembersRows = `-- name: DeleteBusinessMembersRows :exec
DELETE FROM business_members WHERE business_id = $1
`

func (q *Queries) DeleteBusinessMembersRows(ctx context.Context, businessID string) error {
	_, err := q.db.Exec(ctx, deleteBusinessMembersRows, businessID)
	return err
}

const deleteBusinessOrders = `-- name: DeleteBusinessOrders :exec
DELETE FROM orders WHERE business_id = $1
`

func (q *Queries) DeleteBusinessOrders(ctx context.Context, businessID string) error {
	_, err := q.db.Exec(ctx, deleteBusinessOrders, businessID)
	return err
}

const deleteBusinessProducts = `-- name: DeleteBusinessProducts :exec
DELETE FROM products WHERE business_id = $1
`

func (q *Queries) DeleteBusinessProducts(ctx context.Context, businessID string) error {
	_, err := q.db.Exec(ctx, deleteBusinessProducts, businessID)
	return err
}

const deleteBusinessRow = `-- name: DeleteBusinessRow :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) DeleteBusinessRow(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBusinessRow, id)
	return err
}

const deleteBusinessTranscriptMessages = `-- name: DeleteBusinessTranscriptMessages :exec
DELETE FROM transcript_messages
WHERE voice_session_id IN (SELECT id FROM voice_sessions WHERE business_id = $1)
`

func (q *Queries) DeleteBusinessTranscriptMessages(ctx context.Context, businessID string) error {
	_, err := q.db.Exec(ctx, deleteBusinessTranscriptMessages, businessID)
	return err
}

const deleteBusinessUsageEvents = `-- name: DeleteBusinessUsageEvents :exec
DELETE FROM usage_events WHERE business_id = $1
`

func (q *Queries) DeleteBusinessUsageEvents(ctx context.Context, businessID string) error {
	_, err := q.db.Exec(ctx, deleteBusinessUsageEvents, businessID)
	return err
}

const deleteBusinessVoiceSessions = `-- name: DeleteBusinessVoiceSessions :exec
DELETE FROM voice_sessions WHERE business_id = $1
`

func (q *Queries) DeleteBusinessVoiceSessions(ctx context.Context, businessID string) error {
	_, err := q.db.Exec(ctx, deleteBusinessVoiceSessions, businessID)
	return err
}

const getPhotoBrandingPathsForBusiness = `-- name: GetPhotoBrandingPathsForBusiness :one
SELECT logo_url, frame_url FROM photo_settings WHERE business_id = $1
`

type GetPhotoBrandingPathsForBusinessRow struct {
	LogoUrl  pgtype.Text `json:"logo_url"`
	FrameUrl pgtype.Text `json:"frame_url"`
}

func (q *Queries) GetPhotoBrandingPathsForBusiness(ctx context.Context, businessID string) (GetPhotoBrandingPathsForBusinessRow, error) {
	row := q.db.QueryRow(ctx, getPhotoBrandingPathsForBusiness, businessID)
	var i GetPhotoBrandingPathsForBusinessRow
	err := row.Scan(&i.LogoUrl, &i.FrameUrl)
	return i, err
}

const listPhotoStoragePathsForBusiness = `-- name: ListPhotoStoragePathsForBusiness :many
SELECT photo_path, thumbnail_path
FROM photo_sessions
WHERE business_id = $1 AND (photo_path IS NOT NULL OR thumbnail_path IS NOT NULL)
`

type ListPhotoStoragePathsForBusinessRow struct {
	PhotoPath     pgtype.Text `json:"photo_path"`
	ThumbnailPath pgtype.Text `json:"thumbnail_path"`
}

func (q *Queries) ListPhotoStoragePathsForBusiness(ctx context.Context, businessID string) ([]ListPhotoStoragePathsForBusinessRow, error) {
	rows, err := q.db.Query(ctx, listPhotoStoragePathsForBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPhotoStoragePathsForBusinessRow{}
	for rows.Next() {
		var i ListPhotoStoragePathsForBusinessRow
		if err := rows.Scan(&i.PhotoPath, &i.ThumbnailPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresentationStoragePathsForBusiness = `-- name: ListPresentationStoragePathsForBusiness :many

SELECT pf.storage_path
FROM presentation_files pf
JOIN presentations p ON p.id = pf.presentation_id
WHERE p.business_id = $1
`

// Cross-table operational queries backing internal/tenantlifecycle.DeleteBusiness.
// Not owned by any single domain module — sqlc doesn't care which .sql
// file a query is defined in, all land in the shared store package.
func (q *Queries) ListPresentationStoragePathsForBusiness(ctx context.Context, businessID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPresentationStoragePathsForBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var storage_path string
		if err := rows.Scan(&storage_path); err != nil {
			return nil, err
		}
		items = append(items, storage_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
