// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcript_messages.sql

package store

import (
	"context"
)

const countTranscriptMessagesForSessions = `-- name: CountTranscriptMessagesForSessions :many
SELECT voice_session_id, COUNT(*)::int AS message_count
FROM transcript_messages
WHERE voice_session_id = ANY($1::varchar[])
GROUP BY voice_session_id
`

type CountTranscriptMessagesForSessionsRow struct {
	VoiceSessionID string `json:"voice_session_id"`
	MessageCount   int32  `json:"message_count"`
}

func (q *Queries) CountTranscriptMessagesForSessions(ctx context.Context, sessionIds []string) ([]CountTranscriptMessagesForSessionsRow, error) {
	rows, err := q.db.Query(ctx, countTranscriptMessagesForSessions, sessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTranscriptMessagesForSessionsRow{}
	for rows.Next() {
		var i CountTranscriptMessagesForSessionsRow
		if err := rows.Scan(&i.VoiceSessionID, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTranscriptMessage = `-- name: CreateTranscriptMessage :one
INSERT INTO transcript_messages (id, voice_session_id, role, text)
VALUES ($1, $2, $3, $4)
RETURNING id, voice_session_id, role, text, created_at
`

type CreateTranscriptMessageParams struct {
	ID             string `json:"id"`
	VoiceSessionID string `json:"voice_session_id"`
	Role           string `json:"role"`
	Text           string `json:"text"`
}

func (q *Queries) CreateTranscriptMessage(ctx context.Context, arg CreateTranscriptMessageParams) (TranscriptMessage, error) {
	row := q.db.QueryRow(ctx, createTranscriptMessage,
		arg.ID,
		arg.VoiceSessionID,
		arg.Role,
		arg.Text,
	)
	var i TranscriptMessage
	err := row.Scan(
		&i.ID,
		&i.VoiceSessionID,
		&i.Role,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const listTranscriptMessagesForSession = `-- name: ListTranscriptMessagesForSession :many
SELECT id, voice_session_id, role, text, created_at FROM transcript_messages WHERE voice_session_id = $1 ORDER BY created_at
`

func (q *Queries) ListTranscriptMessagesForSession(ctx context.Context, voiceSessionID string) ([]TranscriptMessage, error) {
	rows, err := q.db.Query(ctx, listTranscriptMessagesForSession, voiceSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptMessage{}
	for rows.Next() {
		var i TranscriptMessage
		if err := rows.Scan(
			&i.ID,
			&i.VoiceSessionID,
			&i.Role,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptMessagesForSessions = `-- name: ListTranscriptMessagesForSessions :many
SELECT id, voice_session_id, role, text, created_at FROM transcript_messages
WHERE voice_session_id = ANY($1::varchar[])
ORDER BY created_at
`

func (q *Queries) ListTranscriptMessagesForSessions(ctx context.Context, sessionIds []string) ([]TranscriptMessage, error) {
	rows, err := q.db.Query(ctx, listTranscriptMessagesForSessions, sessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptMessage{}
	for rows.Next() {
		var i TranscriptMessage
		if err := rows.Scan(
			&i.ID,
			&i.VoiceSessionID,
			&i.Role,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
