// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcript_messages.sql

package store

import (
	"context"
)

const createTranscriptMessage = `-- name: CreateTranscriptMessage :one
INSERT INTO transcript_messages (id, voice_session_id, role, text)
VALUES ($1, $2, $3, $4)
RETURNING id, voice_session_id, role, text, created_at
`

type CreateTranscriptMessageParams struct {
	ID             string `json:"id"`
	VoiceSessionID string `json:"voice_session_id"`
	Role           string `json:"role"`
	Text           string `json:"text"`
}

func (q *Queries) CreateTranscriptMessage(ctx context.Context, arg CreateTranscriptMessageParams) (TranscriptMessage, error) {
	row := q.db.QueryRow(ctx, createTranscriptMessage,
		arg.ID,
		arg.VoiceSessionID,
		arg.Role,
		arg.Text,
	)
	var i TranscriptMessage
	err := row.Scan(
		&i.ID,
		&i.VoiceSessionID,
		&i.Role,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}
