// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_events.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsageEventsSince = `-- name: CountUsageEventsSince :one
SELECT count(*) FROM usage_events
WHERE business_id = $1 AND event_type = $2 AND occurred_at >= $3
`

type CountUsageEventsSinceParams struct {
	BusinessID string             `json:"business_id"`
	EventType  string             `json:"event_type"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CountUsageEventsSince(ctx context.Context, arg CountUsageEventsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsageEventsSince, arg.BusinessID, arg.EventType, arg.OccurredAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recordUsageEvent = `-- name: RecordUsageEvent :one
INSERT INTO usage_events (id, business_id, event_type, quantity, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, business_id, event_type, quantity, metadata, occurred_at
`

type RecordUsageEventParams struct {
	ID         string         `json:"id"`
	BusinessID string         `json:"business_id"`
	EventType  string         `json:"event_type"`
	Quantity   pgtype.Numeric `json:"quantity"`
	Metadata   []byte         `json:"metadata"`
}

func (q *Queries) RecordUsageEvent(ctx context.Context, arg RecordUsageEventParams) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, recordUsageEvent,
		arg.ID,
		arg.BusinessID,
		arg.EventType,
		arg.Quantity,
		arg.Metadata,
	)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.EventType,
		&i.Quantity,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}
