// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, status, phone, country, last_login_at, created_at
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.Phone,
		&i.Country,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, status, phone, country, last_login_at, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.Phone,
		&i.Country,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, status, phone, country, last_login_at, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.Phone,
		&i.Country,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserCountry = `-- name: UpdateUserCountry :one
UPDATE users SET country = $2 WHERE id = $1
RETURNING id, email, password_hash, name, status, phone, country, last_login_at, created_at
`

type UpdateUserCountryParams struct {
	ID      string `json:"id"`
	Country string `json:"country"`
}

func (q *Queries) UpdateUserCountry(ctx context.Context, arg UpdateUserCountryParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserCountry, arg.ID, arg.Country)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.Phone,
		&i.Country,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}
