// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voice_sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVoiceSession = `-- name: CreateVoiceSession :one
INSERT INTO voice_sessions (id, business_id)
VALUES ($1, $2)
RETURNING id, business_id, status, end_reason, started_at, ended_at
`

type CreateVoiceSessionParams struct {
	ID         string `json:"id"`
	BusinessID string `json:"business_id"`
}

func (q *Queries) CreateVoiceSession(ctx context.Context, arg CreateVoiceSessionParams) (VoiceSession, error) {
	row := q.db.QueryRow(ctx, createVoiceSession, arg.ID, arg.BusinessID)
	var i VoiceSession
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Status,
		&i.EndReason,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const endVoiceSession = `-- name: EndVoiceSession :exec
UPDATE voice_sessions SET status = 'ended', end_reason = $2, ended_at = NOW()
WHERE id = $1
`

type EndVoiceSessionParams struct {
	ID        string      `json:"id"`
	EndReason pgtype.Text `json:"end_reason"`
}

func (q *Queries) EndVoiceSession(ctx context.Context, arg EndVoiceSessionParams) error {
	_, err := q.db.Exec(ctx, endVoiceSession, arg.ID, arg.EndReason)
	return err
}
