services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voicetalk
    volumes:
      - voicetalk_pg:/var/lib/postgresql/data

volumes:
  voicetalk_pg:
